// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AvatarTeamResonanceInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from AvatarTeamResonanceInfo.proto</summary>
  public static partial class AvatarTeamResonanceInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for AvatarTeamResonanceInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AvatarTeamResonanceInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1BdmF0YXJUZWFtUmVzb25hbmNlSW5mby5wcm90bxIfV2VlZHdhY2tlci5T",
            "aGFyZWQuTmV0d29yay5Qcm90byJ7ChdBdmF0YXJUZWFtUmVzb25hbmNlSW5m",
            "bxITCgthdmF0YXJfZ3VpZBgJIAEoBBIRCgllbnRpdHlfaWQYCCABKA0SGwoT",
            "VW5rMzMwMF9NQkpFRUVFRUpDRRgPIAMoDRIbChNVbmszMzAwX0xQQUtHR0JC",
            "RE5KGA0gAygNYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.AvatarTeamResonanceInfo), global::Weedwacker.Shared.Network.Proto.AvatarTeamResonanceInfo.Parser, new[]{ "AvatarGuid", "EntityId", "Unk3300MBJEEEEEJCE", "Unk3300LPAKGGBBDNJ" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AvatarTeamResonanceInfo : pb::IMessage<AvatarTeamResonanceInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AvatarTeamResonanceInfo> _parser = new pb::MessageParser<AvatarTeamResonanceInfo>(() => new AvatarTeamResonanceInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AvatarTeamResonanceInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.AvatarTeamResonanceInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AvatarTeamResonanceInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AvatarTeamResonanceInfo(AvatarTeamResonanceInfo other) : this() {
      avatarGuid_ = other.avatarGuid_;
      entityId_ = other.entityId_;
      unk3300MBJEEEEEJCE_ = other.unk3300MBJEEEEEJCE_.Clone();
      unk3300LPAKGGBBDNJ_ = other.unk3300LPAKGGBBDNJ_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AvatarTeamResonanceInfo Clone() {
      return new AvatarTeamResonanceInfo(this);
    }

    /// <summary>Field number for the "avatar_guid" field.</summary>
    public const int AvatarGuidFieldNumber = 9;
    private ulong avatarGuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong AvatarGuid {
      get { return avatarGuid_; }
      set {
        avatarGuid_ = value;
      }
    }

    /// <summary>Field number for the "entity_id" field.</summary>
    public const int EntityIdFieldNumber = 8;
    private uint entityId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EntityId {
      get { return entityId_; }
      set {
        entityId_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_MBJEEEEEJCE" field.</summary>
    public const int Unk3300MBJEEEEEJCEFieldNumber = 15;
    private static readonly pb::FieldCodec<uint> _repeated_unk3300MBJEEEEEJCE_codec
        = pb::FieldCodec.ForUInt32(122);
    private readonly pbc::RepeatedField<uint> unk3300MBJEEEEEJCE_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Unk3300MBJEEEEEJCE {
      get { return unk3300MBJEEEEEJCE_; }
    }

    /// <summary>Field number for the "Unk3300_LPAKGGBBDNJ" field.</summary>
    public const int Unk3300LPAKGGBBDNJFieldNumber = 13;
    private static readonly pb::FieldCodec<uint> _repeated_unk3300LPAKGGBBDNJ_codec
        = pb::FieldCodec.ForUInt32(106);
    private readonly pbc::RepeatedField<uint> unk3300LPAKGGBBDNJ_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Unk3300LPAKGGBBDNJ {
      get { return unk3300LPAKGGBBDNJ_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AvatarTeamResonanceInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AvatarTeamResonanceInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AvatarGuid != other.AvatarGuid) return false;
      if (EntityId != other.EntityId) return false;
      if(!unk3300MBJEEEEEJCE_.Equals(other.unk3300MBJEEEEEJCE_)) return false;
      if(!unk3300LPAKGGBBDNJ_.Equals(other.unk3300LPAKGGBBDNJ_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AvatarGuid != 0UL) hash ^= AvatarGuid.GetHashCode();
      if (EntityId != 0) hash ^= EntityId.GetHashCode();
      hash ^= unk3300MBJEEEEEJCE_.GetHashCode();
      hash ^= unk3300LPAKGGBBDNJ_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EntityId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(EntityId);
      }
      if (AvatarGuid != 0UL) {
        output.WriteRawTag(72);
        output.WriteUInt64(AvatarGuid);
      }
      unk3300LPAKGGBBDNJ_.WriteTo(output, _repeated_unk3300LPAKGGBBDNJ_codec);
      unk3300MBJEEEEEJCE_.WriteTo(output, _repeated_unk3300MBJEEEEEJCE_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EntityId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(EntityId);
      }
      if (AvatarGuid != 0UL) {
        output.WriteRawTag(72);
        output.WriteUInt64(AvatarGuid);
      }
      unk3300LPAKGGBBDNJ_.WriteTo(ref output, _repeated_unk3300LPAKGGBBDNJ_codec);
      unk3300MBJEEEEEJCE_.WriteTo(ref output, _repeated_unk3300MBJEEEEEJCE_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AvatarGuid != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(AvatarGuid);
      }
      if (EntityId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EntityId);
      }
      size += unk3300MBJEEEEEJCE_.CalculateSize(_repeated_unk3300MBJEEEEEJCE_codec);
      size += unk3300LPAKGGBBDNJ_.CalculateSize(_repeated_unk3300LPAKGGBBDNJ_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AvatarTeamResonanceInfo other) {
      if (other == null) {
        return;
      }
      if (other.AvatarGuid != 0UL) {
        AvatarGuid = other.AvatarGuid;
      }
      if (other.EntityId != 0) {
        EntityId = other.EntityId;
      }
      unk3300MBJEEEEEJCE_.Add(other.unk3300MBJEEEEEJCE_);
      unk3300LPAKGGBBDNJ_.Add(other.unk3300LPAKGGBBDNJ_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 64: {
            EntityId = input.ReadUInt32();
            break;
          }
          case 72: {
            AvatarGuid = input.ReadUInt64();
            break;
          }
          case 106:
          case 104: {
            unk3300LPAKGGBBDNJ_.AddEntriesFrom(input, _repeated_unk3300LPAKGGBBDNJ_codec);
            break;
          }
          case 122:
          case 120: {
            unk3300MBJEEEEEJCE_.AddEntriesFrom(input, _repeated_unk3300MBJEEEEEJCE_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 64: {
            EntityId = input.ReadUInt32();
            break;
          }
          case 72: {
            AvatarGuid = input.ReadUInt64();
            break;
          }
          case 106:
          case 104: {
            unk3300LPAKGGBBDNJ_.AddEntriesFrom(ref input, _repeated_unk3300LPAKGGBBDNJ_codec);
            break;
          }
          case 122:
          case 120: {
            unk3300MBJEEEEEJCE_.AddEntriesFrom(ref input, _repeated_unk3300MBJEEEEEJCE_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
