// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BattlePassSchedule.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from BattlePassSchedule.proto</summary>
  public static partial class BattlePassScheduleReflection {

    #region Descriptor
    /// <summary>File descriptor for BattlePassSchedule.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BattlePassScheduleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhCYXR0bGVQYXNzU2NoZWR1bGUucHJvdG8SH1dlZWR3YWNrZXIuU2hhcmVk",
            "Lk5ldHdvcmsuUHJvdG8aFUJhdHRsZVBhc3NDeWNsZS5wcm90bxoXQmF0dGxl",
            "UGFzc1Byb2R1Y3QucHJvdG8aGUJhdHRsZVBhc3NSZXdhcmRUYWcucHJvdG8a",
            "HEJhdHRsZVBhc3NVbmxvY2tTdGF0dXMucHJvdG8ihAQKEkJhdHRsZVBhc3NT",
            "Y2hlZHVsZRITCgtzY2hlZHVsZV9pZBgFIAEoDRINCgVwb2ludBgCIAEoDRIN",
            "CgVsZXZlbBgHIAEoDRIbChNVbmszMzAwX0tPREZKRU5DSkxFGAggASgIEhgK",
            "EGN1cl9jeWNsZV9wb2ludHMYDiABKA0SEQoJaXNfdmlld2VkGAwgASgIEhsK",
            "E1VuazMzMDBfRklMQ0lQUEFISEwYBCABKA0SQwoJY3VyX2N5Y2xlGAsgASgL",
            "MjAuV2VlZHdhY2tlci5TaGFyZWQuTmV0d29yay5Qcm90by5CYXR0bGVQYXNz",
            "Q3ljbGUSEgoKYmVnaW5fdGltZRgBIAEoDRJOCg11bmxvY2tfc3RhdHVzGA8g",
            "ASgOMjcuV2VlZHdhY2tlci5TaGFyZWQuTmV0d29yay5Qcm90by5CYXR0bGVQ",
            "YXNzVW5sb2NrU3RhdHVzEkgKDHByb2R1Y3RfaW5mbxgKIAEoCzIyLldlZWR3",
            "YWNrZXIuU2hhcmVkLk5ldHdvcmsuUHJvdG8uQmF0dGxlUGFzc1Byb2R1Y3QS",
            "EAoIZW5kX3RpbWUYDSABKA0STwoRcmV3YXJkX3Rha2VuX2xpc3QYAyADKAsy",
            "NC5XZWVkd2Fja2VyLlNoYXJlZC5OZXR3b3JrLlByb3RvLkJhdHRsZVBhc3NS",
            "ZXdhcmRUYWdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Weedwacker.Shared.Network.Proto.BattlePassCycleReflection.Descriptor, global::Weedwacker.Shared.Network.Proto.BattlePassProductReflection.Descriptor, global::Weedwacker.Shared.Network.Proto.BattlePassRewardTagReflection.Descriptor, global::Weedwacker.Shared.Network.Proto.BattlePassUnlockStatusReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.BattlePassSchedule), global::Weedwacker.Shared.Network.Proto.BattlePassSchedule.Parser, new[]{ "ScheduleId", "Point", "Level", "Unk3300KODFJENCJLE", "CurCyclePoints", "IsViewed", "Unk3300FILCIPPAHHL", "CurCycle", "BeginTime", "UnlockStatus", "ProductInfo", "EndTime", "RewardTakenList" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class BattlePassSchedule : pb::IMessage<BattlePassSchedule>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BattlePassSchedule> _parser = new pb::MessageParser<BattlePassSchedule>(() => new BattlePassSchedule());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BattlePassSchedule> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.BattlePassScheduleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattlePassSchedule() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattlePassSchedule(BattlePassSchedule other) : this() {
      scheduleId_ = other.scheduleId_;
      point_ = other.point_;
      level_ = other.level_;
      unk3300KODFJENCJLE_ = other.unk3300KODFJENCJLE_;
      curCyclePoints_ = other.curCyclePoints_;
      isViewed_ = other.isViewed_;
      unk3300FILCIPPAHHL_ = other.unk3300FILCIPPAHHL_;
      curCycle_ = other.curCycle_ != null ? other.curCycle_.Clone() : null;
      beginTime_ = other.beginTime_;
      unlockStatus_ = other.unlockStatus_;
      productInfo_ = other.productInfo_ != null ? other.productInfo_.Clone() : null;
      endTime_ = other.endTime_;
      rewardTakenList_ = other.rewardTakenList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattlePassSchedule Clone() {
      return new BattlePassSchedule(this);
    }

    /// <summary>Field number for the "schedule_id" field.</summary>
    public const int ScheduleIdFieldNumber = 5;
    private uint scheduleId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ScheduleId {
      get { return scheduleId_; }
      set {
        scheduleId_ = value;
      }
    }

    /// <summary>Field number for the "point" field.</summary>
    public const int PointFieldNumber = 2;
    private uint point_;
    /// <summary>
    /// Unk3300_MAAJDKMIODC
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Point {
      get { return point_; }
      set {
        point_ = value;
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 7;
    private uint level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_KODFJENCJLE" field.</summary>
    public const int Unk3300KODFJENCJLEFieldNumber = 8;
    private bool unk3300KODFJENCJLE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unk3300KODFJENCJLE {
      get { return unk3300KODFJENCJLE_; }
      set {
        unk3300KODFJENCJLE_ = value;
      }
    }

    /// <summary>Field number for the "cur_cycle_points" field.</summary>
    public const int CurCyclePointsFieldNumber = 14;
    private uint curCyclePoints_;
    /// <summary>
    /// Unk3300_ELMNFBOLEOA
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CurCyclePoints {
      get { return curCyclePoints_; }
      set {
        curCyclePoints_ = value;
      }
    }

    /// <summary>Field number for the "is_viewed" field.</summary>
    public const int IsViewedFieldNumber = 12;
    private bool isViewed_;
    /// <summary>
    /// Unk3300_KALOGHHMJJE
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsViewed {
      get { return isViewed_; }
      set {
        isViewed_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_FILCIPPAHHL" field.</summary>
    public const int Unk3300FILCIPPAHHLFieldNumber = 4;
    private uint unk3300FILCIPPAHHL_;
    /// <summary>
    /// Unk3300_FILCIPPAHHL
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Unk3300FILCIPPAHHL {
      get { return unk3300FILCIPPAHHL_; }
      set {
        unk3300FILCIPPAHHL_ = value;
      }
    }

    /// <summary>Field number for the "cur_cycle" field.</summary>
    public const int CurCycleFieldNumber = 11;
    private global::Weedwacker.Shared.Network.Proto.BattlePassCycle curCycle_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.BattlePassCycle CurCycle {
      get { return curCycle_; }
      set {
        curCycle_ = value;
      }
    }

    /// <summary>Field number for the "begin_time" field.</summary>
    public const int BeginTimeFieldNumber = 1;
    private uint beginTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BeginTime {
      get { return beginTime_; }
      set {
        beginTime_ = value;
      }
    }

    /// <summary>Field number for the "unlock_status" field.</summary>
    public const int UnlockStatusFieldNumber = 15;
    private global::Weedwacker.Shared.Network.Proto.BattlePassUnlockStatus unlockStatus_ = global::Weedwacker.Shared.Network.Proto.BattlePassUnlockStatus.Invalid;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.BattlePassUnlockStatus UnlockStatus {
      get { return unlockStatus_; }
      set {
        unlockStatus_ = value;
      }
    }

    /// <summary>Field number for the "product_info" field.</summary>
    public const int ProductInfoFieldNumber = 10;
    private global::Weedwacker.Shared.Network.Proto.BattlePassProduct productInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.BattlePassProduct ProductInfo {
      get { return productInfo_; }
      set {
        productInfo_ = value;
      }
    }

    /// <summary>Field number for the "end_time" field.</summary>
    public const int EndTimeFieldNumber = 13;
    private uint endTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EndTime {
      get { return endTime_; }
      set {
        endTime_ = value;
      }
    }

    /// <summary>Field number for the "reward_taken_list" field.</summary>
    public const int RewardTakenListFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Weedwacker.Shared.Network.Proto.BattlePassRewardTag> _repeated_rewardTakenList_codec
        = pb::FieldCodec.ForMessage(26, global::Weedwacker.Shared.Network.Proto.BattlePassRewardTag.Parser);
    private readonly pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.BattlePassRewardTag> rewardTakenList_ = new pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.BattlePassRewardTag>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.BattlePassRewardTag> RewardTakenList {
      get { return rewardTakenList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BattlePassSchedule);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BattlePassSchedule other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ScheduleId != other.ScheduleId) return false;
      if (Point != other.Point) return false;
      if (Level != other.Level) return false;
      if (Unk3300KODFJENCJLE != other.Unk3300KODFJENCJLE) return false;
      if (CurCyclePoints != other.CurCyclePoints) return false;
      if (IsViewed != other.IsViewed) return false;
      if (Unk3300FILCIPPAHHL != other.Unk3300FILCIPPAHHL) return false;
      if (!object.Equals(CurCycle, other.CurCycle)) return false;
      if (BeginTime != other.BeginTime) return false;
      if (UnlockStatus != other.UnlockStatus) return false;
      if (!object.Equals(ProductInfo, other.ProductInfo)) return false;
      if (EndTime != other.EndTime) return false;
      if(!rewardTakenList_.Equals(other.rewardTakenList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ScheduleId != 0) hash ^= ScheduleId.GetHashCode();
      if (Point != 0) hash ^= Point.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (Unk3300KODFJENCJLE != false) hash ^= Unk3300KODFJENCJLE.GetHashCode();
      if (CurCyclePoints != 0) hash ^= CurCyclePoints.GetHashCode();
      if (IsViewed != false) hash ^= IsViewed.GetHashCode();
      if (Unk3300FILCIPPAHHL != 0) hash ^= Unk3300FILCIPPAHHL.GetHashCode();
      if (curCycle_ != null) hash ^= CurCycle.GetHashCode();
      if (BeginTime != 0) hash ^= BeginTime.GetHashCode();
      if (UnlockStatus != global::Weedwacker.Shared.Network.Proto.BattlePassUnlockStatus.Invalid) hash ^= UnlockStatus.GetHashCode();
      if (productInfo_ != null) hash ^= ProductInfo.GetHashCode();
      if (EndTime != 0) hash ^= EndTime.GetHashCode();
      hash ^= rewardTakenList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BeginTime != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(BeginTime);
      }
      if (Point != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Point);
      }
      rewardTakenList_.WriteTo(output, _repeated_rewardTakenList_codec);
      if (Unk3300FILCIPPAHHL != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Unk3300FILCIPPAHHL);
      }
      if (ScheduleId != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(ScheduleId);
      }
      if (Level != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(Level);
      }
      if (Unk3300KODFJENCJLE != false) {
        output.WriteRawTag(64);
        output.WriteBool(Unk3300KODFJENCJLE);
      }
      if (productInfo_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(ProductInfo);
      }
      if (curCycle_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(CurCycle);
      }
      if (IsViewed != false) {
        output.WriteRawTag(96);
        output.WriteBool(IsViewed);
      }
      if (EndTime != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(EndTime);
      }
      if (CurCyclePoints != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(CurCyclePoints);
      }
      if (UnlockStatus != global::Weedwacker.Shared.Network.Proto.BattlePassUnlockStatus.Invalid) {
        output.WriteRawTag(120);
        output.WriteEnum((int) UnlockStatus);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BeginTime != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(BeginTime);
      }
      if (Point != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Point);
      }
      rewardTakenList_.WriteTo(ref output, _repeated_rewardTakenList_codec);
      if (Unk3300FILCIPPAHHL != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Unk3300FILCIPPAHHL);
      }
      if (ScheduleId != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(ScheduleId);
      }
      if (Level != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(Level);
      }
      if (Unk3300KODFJENCJLE != false) {
        output.WriteRawTag(64);
        output.WriteBool(Unk3300KODFJENCJLE);
      }
      if (productInfo_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(ProductInfo);
      }
      if (curCycle_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(CurCycle);
      }
      if (IsViewed != false) {
        output.WriteRawTag(96);
        output.WriteBool(IsViewed);
      }
      if (EndTime != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(EndTime);
      }
      if (CurCyclePoints != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(CurCyclePoints);
      }
      if (UnlockStatus != global::Weedwacker.Shared.Network.Proto.BattlePassUnlockStatus.Invalid) {
        output.WriteRawTag(120);
        output.WriteEnum((int) UnlockStatus);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ScheduleId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ScheduleId);
      }
      if (Point != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Point);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Level);
      }
      if (Unk3300KODFJENCJLE != false) {
        size += 1 + 1;
      }
      if (CurCyclePoints != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CurCyclePoints);
      }
      if (IsViewed != false) {
        size += 1 + 1;
      }
      if (Unk3300FILCIPPAHHL != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Unk3300FILCIPPAHHL);
      }
      if (curCycle_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CurCycle);
      }
      if (BeginTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BeginTime);
      }
      if (UnlockStatus != global::Weedwacker.Shared.Network.Proto.BattlePassUnlockStatus.Invalid) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UnlockStatus);
      }
      if (productInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ProductInfo);
      }
      if (EndTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EndTime);
      }
      size += rewardTakenList_.CalculateSize(_repeated_rewardTakenList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BattlePassSchedule other) {
      if (other == null) {
        return;
      }
      if (other.ScheduleId != 0) {
        ScheduleId = other.ScheduleId;
      }
      if (other.Point != 0) {
        Point = other.Point;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.Unk3300KODFJENCJLE != false) {
        Unk3300KODFJENCJLE = other.Unk3300KODFJENCJLE;
      }
      if (other.CurCyclePoints != 0) {
        CurCyclePoints = other.CurCyclePoints;
      }
      if (other.IsViewed != false) {
        IsViewed = other.IsViewed;
      }
      if (other.Unk3300FILCIPPAHHL != 0) {
        Unk3300FILCIPPAHHL = other.Unk3300FILCIPPAHHL;
      }
      if (other.curCycle_ != null) {
        if (curCycle_ == null) {
          CurCycle = new global::Weedwacker.Shared.Network.Proto.BattlePassCycle();
        }
        CurCycle.MergeFrom(other.CurCycle);
      }
      if (other.BeginTime != 0) {
        BeginTime = other.BeginTime;
      }
      if (other.UnlockStatus != global::Weedwacker.Shared.Network.Proto.BattlePassUnlockStatus.Invalid) {
        UnlockStatus = other.UnlockStatus;
      }
      if (other.productInfo_ != null) {
        if (productInfo_ == null) {
          ProductInfo = new global::Weedwacker.Shared.Network.Proto.BattlePassProduct();
        }
        ProductInfo.MergeFrom(other.ProductInfo);
      }
      if (other.EndTime != 0) {
        EndTime = other.EndTime;
      }
      rewardTakenList_.Add(other.rewardTakenList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BeginTime = input.ReadUInt32();
            break;
          }
          case 16: {
            Point = input.ReadUInt32();
            break;
          }
          case 26: {
            rewardTakenList_.AddEntriesFrom(input, _repeated_rewardTakenList_codec);
            break;
          }
          case 32: {
            Unk3300FILCIPPAHHL = input.ReadUInt32();
            break;
          }
          case 40: {
            ScheduleId = input.ReadUInt32();
            break;
          }
          case 56: {
            Level = input.ReadUInt32();
            break;
          }
          case 64: {
            Unk3300KODFJENCJLE = input.ReadBool();
            break;
          }
          case 82: {
            if (productInfo_ == null) {
              ProductInfo = new global::Weedwacker.Shared.Network.Proto.BattlePassProduct();
            }
            input.ReadMessage(ProductInfo);
            break;
          }
          case 90: {
            if (curCycle_ == null) {
              CurCycle = new global::Weedwacker.Shared.Network.Proto.BattlePassCycle();
            }
            input.ReadMessage(CurCycle);
            break;
          }
          case 96: {
            IsViewed = input.ReadBool();
            break;
          }
          case 104: {
            EndTime = input.ReadUInt32();
            break;
          }
          case 112: {
            CurCyclePoints = input.ReadUInt32();
            break;
          }
          case 120: {
            UnlockStatus = (global::Weedwacker.Shared.Network.Proto.BattlePassUnlockStatus) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BeginTime = input.ReadUInt32();
            break;
          }
          case 16: {
            Point = input.ReadUInt32();
            break;
          }
          case 26: {
            rewardTakenList_.AddEntriesFrom(ref input, _repeated_rewardTakenList_codec);
            break;
          }
          case 32: {
            Unk3300FILCIPPAHHL = input.ReadUInt32();
            break;
          }
          case 40: {
            ScheduleId = input.ReadUInt32();
            break;
          }
          case 56: {
            Level = input.ReadUInt32();
            break;
          }
          case 64: {
            Unk3300KODFJENCJLE = input.ReadBool();
            break;
          }
          case 82: {
            if (productInfo_ == null) {
              ProductInfo = new global::Weedwacker.Shared.Network.Proto.BattlePassProduct();
            }
            input.ReadMessage(ProductInfo);
            break;
          }
          case 90: {
            if (curCycle_ == null) {
              CurCycle = new global::Weedwacker.Shared.Network.Proto.BattlePassCycle();
            }
            input.ReadMessage(CurCycle);
            break;
          }
          case 96: {
            IsViewed = input.ReadBool();
            break;
          }
          case 104: {
            EndTime = input.ReadUInt32();
            break;
          }
          case 112: {
            CurCyclePoints = input.ReadUInt32();
            break;
          }
          case 120: {
            UnlockStatus = (global::Weedwacker.Shared.Network.Proto.BattlePassUnlockStatus) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
