// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: FireWorkType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from FireWorkType.proto</summary>
  public static partial class FireWorkTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for FireWorkType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FireWorkTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJGaXJlV29ya1R5cGUucHJvdG8SH1dlZWR3YWNrZXIuU2hhcmVkLk5ldHdv",
            "cmsuUHJvdG8qwgEKDEZpcmVXb3JrVHlwZRIcChhGaXJlV29ya1R5cGVfT0RK",
            "S0FOS01QUEoQABIcChhGaXJlV29ya1R5cGVfRUZHTEhFSU9ERk4QARIcChhG",
            "aXJlV29ya1R5cGVfSlBCQkJDRkdIQUsQAhIcChhGaXJlV29ya1R5cGVfSURD",
            "TUdIQkhCRkgQAxIcChhGaXJlV29ya1R5cGVfT0REQk5OREZNQk8QBBIcChhG",
            "aXJlV29ya1R5cGVfQUdJRE1PR0pPQkQQBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Weedwacker.Shared.Network.Proto.FireWorkType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum FireWorkType {
    [pbr::OriginalName("FireWorkType_ODJKANKMPPJ")] Odjkankmppj = 0,
    [pbr::OriginalName("FireWorkType_EFGLHEIODFN")] Efglheiodfn = 1,
    [pbr::OriginalName("FireWorkType_JPBBBCFGHAK")] Jpbbbcfghak = 2,
    [pbr::OriginalName("FireWorkType_IDCMGHBHBFH")] Idcmghbhbfh = 3,
    [pbr::OriginalName("FireWorkType_ODDBNNDFMBO")] Oddbnndfmbo = 4,
    [pbr::OriginalName("FireWorkType_AGIDMOGJOBD")] Agidmogjobd = 5,
  }

  #endregion

}

#endregion Designer generated code
