// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GachaInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from GachaInfo.proto</summary>
  public static partial class GachaInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for GachaInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GachaInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9HYWNoYUluZm8ucHJvdG8SH1dlZWR3YWNrZXIuU2hhcmVkLk5ldHdvcmsu",
            "UHJvdG8aEUdhY2hhVXBJbmZvLnByb3RvIt0FCglHYWNoYUluZm8SFAoMY29z",
            "dF9pdGVtX2lkGAUgASgNEhIKCmdhY2hhX3R5cGUYByABKA0SFgoNY29zdF9p",
            "dGVtX251bRi6ByABKA0SGgoRZ2FjaGFfcHJlZmFiX3BhdGgY/AsgASgJEiEK",
            "GWdhY2hhX3ByZXZpZXdfcHJlZmFiX3BhdGgYDyABKAkSFgoOZ2FjaGFfcHJv",
            "Yl91cmwYASABKAkSEgoKYmVnaW5fdGltZRgOIAEoDRITCgtzY2hlZHVsZV9p",
            "ZBgIIAEoDRIeChVkaXNwbGF5X3VwNV9pdGVtX2xpc3QY3AMgAygNEhgKEHRl",
            "bl9jb3N0X2l0ZW1faWQYCiABKA0SHgoWZ2FjaGFfcHJvYl91cmxfb3ZlcnNl",
            "YRgEIAEoCRIYChBnYWNoYV9yZWNvcmRfdXJsGHIgASgJEhoKEXRlbl9jb3N0",
            "X2l0ZW1fbnVtGPUBIAEoDRIQCghlbmRfdGltZRgCIAEoDRIeChVkaXNwbGF5",
            "X3VwNF9pdGVtX2xpc3QYnAQgAygNEhgKEGxlZnRfZ2FjaGFfdGltZXMYDSAB",
            "KA0SGgoRZ2FjaGFfdGltZXNfbGltaXQY+wkgASgNEhUKDWdhY2hhX3NvcnRf",
            "aWQYCSABKA0SFAoMd2lzaF9pdGVtX2lkGAYgASgNEhQKC2lzX25ld193aXNo",
            "GMcHIAEoCBIVCg13aXNoX3Byb2dyZXNzGAwgASgNEhoKEXdpc2hfbWF4X3By",
            "b2dyZXNzGKwMIAEoDRIhChhnYWNoYV9yZWNvcmRfdXJsX292ZXJzZWEY6wkg",
            "ASgJEkkKEmdhY2hhX3VwX2luZm9fbGlzdBixDCADKAsyLC5XZWVkd2Fja2Vy",
            "LlNoYXJlZC5OZXR3b3JrLlByb3RvLkdhY2hhVXBJbmZvEhsKE1VuazMzMDBf",
            "UExGTU1PRk5HQUcYAyABKA0SFQoNdGl0bGVfdGV4dG1hcBgLIAEoCWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Weedwacker.Shared.Network.Proto.GachaUpInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.GachaInfo), global::Weedwacker.Shared.Network.Proto.GachaInfo.Parser, new[]{ "CostItemId", "GachaType", "CostItemNum", "GachaPrefabPath", "GachaPreviewPrefabPath", "GachaProbUrl", "BeginTime", "ScheduleId", "DisplayUp5ItemList", "TenCostItemId", "GachaProbUrlOversea", "GachaRecordUrl", "TenCostItemNum", "EndTime", "DisplayUp4ItemList", "LeftGachaTimes", "GachaTimesLimit", "GachaSortId", "WishItemId", "IsNewWish", "WishProgress", "WishMaxProgress", "GachaRecordUrlOversea", "GachaUpInfoList", "Unk3300PLFMMOFNGAG", "TitleTextmap" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GachaInfo : pb::IMessage<GachaInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GachaInfo> _parser = new pb::MessageParser<GachaInfo>(() => new GachaInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GachaInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.GachaInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GachaInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GachaInfo(GachaInfo other) : this() {
      costItemId_ = other.costItemId_;
      gachaType_ = other.gachaType_;
      costItemNum_ = other.costItemNum_;
      gachaPrefabPath_ = other.gachaPrefabPath_;
      gachaPreviewPrefabPath_ = other.gachaPreviewPrefabPath_;
      gachaProbUrl_ = other.gachaProbUrl_;
      beginTime_ = other.beginTime_;
      scheduleId_ = other.scheduleId_;
      displayUp5ItemList_ = other.displayUp5ItemList_.Clone();
      tenCostItemId_ = other.tenCostItemId_;
      gachaProbUrlOversea_ = other.gachaProbUrlOversea_;
      gachaRecordUrl_ = other.gachaRecordUrl_;
      tenCostItemNum_ = other.tenCostItemNum_;
      endTime_ = other.endTime_;
      displayUp4ItemList_ = other.displayUp4ItemList_.Clone();
      leftGachaTimes_ = other.leftGachaTimes_;
      gachaTimesLimit_ = other.gachaTimesLimit_;
      gachaSortId_ = other.gachaSortId_;
      wishItemId_ = other.wishItemId_;
      isNewWish_ = other.isNewWish_;
      wishProgress_ = other.wishProgress_;
      wishMaxProgress_ = other.wishMaxProgress_;
      gachaRecordUrlOversea_ = other.gachaRecordUrlOversea_;
      gachaUpInfoList_ = other.gachaUpInfoList_.Clone();
      unk3300PLFMMOFNGAG_ = other.unk3300PLFMMOFNGAG_;
      titleTextmap_ = other.titleTextmap_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GachaInfo Clone() {
      return new GachaInfo(this);
    }

    /// <summary>Field number for the "cost_item_id" field.</summary>
    public const int CostItemIdFieldNumber = 5;
    private uint costItemId_;
    /// <summary>
    /// Unk3300_JLELMHELIDC
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CostItemId {
      get { return costItemId_; }
      set {
        costItemId_ = value;
      }
    }

    /// <summary>Field number for the "gacha_type" field.</summary>
    public const int GachaTypeFieldNumber = 7;
    private uint gachaType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GachaType {
      get { return gachaType_; }
      set {
        gachaType_ = value;
      }
    }

    /// <summary>Field number for the "cost_item_num" field.</summary>
    public const int CostItemNumFieldNumber = 954;
    private uint costItemNum_;
    /// <summary>
    /// Unk3300_NMOKGFGDFFC
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CostItemNum {
      get { return costItemNum_; }
      set {
        costItemNum_ = value;
      }
    }

    /// <summary>Field number for the "gacha_prefab_path" field.</summary>
    public const int GachaPrefabPathFieldNumber = 1532;
    private string gachaPrefabPath_ = "";
    /// <summary>
    /// Unk3300_GKDEEFNFCAC
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GachaPrefabPath {
      get { return gachaPrefabPath_; }
      set {
        gachaPrefabPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gacha_preview_prefab_path" field.</summary>
    public const int GachaPreviewPrefabPathFieldNumber = 15;
    private string gachaPreviewPrefabPath_ = "";
    /// <summary>
    /// Unk3300_FOGPKBALHPI
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GachaPreviewPrefabPath {
      get { return gachaPreviewPrefabPath_; }
      set {
        gachaPreviewPrefabPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gacha_prob_url" field.</summary>
    public const int GachaProbUrlFieldNumber = 1;
    private string gachaProbUrl_ = "";
    /// <summary>
    /// Unk3300_HLPKLMGIBIB
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GachaProbUrl {
      get { return gachaProbUrl_; }
      set {
        gachaProbUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "begin_time" field.</summary>
    public const int BeginTimeFieldNumber = 14;
    private uint beginTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BeginTime {
      get { return beginTime_; }
      set {
        beginTime_ = value;
      }
    }

    /// <summary>Field number for the "schedule_id" field.</summary>
    public const int ScheduleIdFieldNumber = 8;
    private uint scheduleId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ScheduleId {
      get { return scheduleId_; }
      set {
        scheduleId_ = value;
      }
    }

    /// <summary>Field number for the "display_up5_item_list" field.</summary>
    public const int DisplayUp5ItemListFieldNumber = 476;
    private static readonly pb::FieldCodec<uint> _repeated_displayUp5ItemList_codec
        = pb::FieldCodec.ForUInt32(3810);
    private readonly pbc::RepeatedField<uint> displayUp5ItemList_ = new pbc::RepeatedField<uint>();
    /// <summary>
    /// Unk3300_LBLEBDLJDLL
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> DisplayUp5ItemList {
      get { return displayUp5ItemList_; }
    }

    /// <summary>Field number for the "ten_cost_item_id" field.</summary>
    public const int TenCostItemIdFieldNumber = 10;
    private uint tenCostItemId_;
    /// <summary>
    /// Unk3300_GLPMIEMBGGL
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TenCostItemId {
      get { return tenCostItemId_; }
      set {
        tenCostItemId_ = value;
      }
    }

    /// <summary>Field number for the "gacha_prob_url_oversea" field.</summary>
    public const int GachaProbUrlOverseaFieldNumber = 4;
    private string gachaProbUrlOversea_ = "";
    /// <summary>
    /// Unk3300_BCJONGECBOH
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GachaProbUrlOversea {
      get { return gachaProbUrlOversea_; }
      set {
        gachaProbUrlOversea_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gacha_record_url" field.</summary>
    public const int GachaRecordUrlFieldNumber = 114;
    private string gachaRecordUrl_ = "";
    /// <summary>
    /// Unk3300_JOGAHFBKHNJ
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GachaRecordUrl {
      get { return gachaRecordUrl_; }
      set {
        gachaRecordUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ten_cost_item_num" field.</summary>
    public const int TenCostItemNumFieldNumber = 245;
    private uint tenCostItemNum_;
    /// <summary>
    /// Unk3300_HLANONBCBLM
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TenCostItemNum {
      get { return tenCostItemNum_; }
      set {
        tenCostItemNum_ = value;
      }
    }

    /// <summary>Field number for the "end_time" field.</summary>
    public const int EndTimeFieldNumber = 2;
    private uint endTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EndTime {
      get { return endTime_; }
      set {
        endTime_ = value;
      }
    }

    /// <summary>Field number for the "display_up4_item_list" field.</summary>
    public const int DisplayUp4ItemListFieldNumber = 540;
    private static readonly pb::FieldCodec<uint> _repeated_displayUp4ItemList_codec
        = pb::FieldCodec.ForUInt32(4322);
    private readonly pbc::RepeatedField<uint> displayUp4ItemList_ = new pbc::RepeatedField<uint>();
    /// <summary>
    /// Unk3300_COABNBJCKEO
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> DisplayUp4ItemList {
      get { return displayUp4ItemList_; }
    }

    /// <summary>Field number for the "left_gacha_times" field.</summary>
    public const int LeftGachaTimesFieldNumber = 13;
    private uint leftGachaTimes_;
    /// <summary>
    /// Unk3300_MEDMCPFCIOO
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LeftGachaTimes {
      get { return leftGachaTimes_; }
      set {
        leftGachaTimes_ = value;
      }
    }

    /// <summary>Field number for the "gacha_times_limit" field.</summary>
    public const int GachaTimesLimitFieldNumber = 1275;
    private uint gachaTimesLimit_;
    /// <summary>
    /// Unk3300_BLLMPAJNCPI
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GachaTimesLimit {
      get { return gachaTimesLimit_; }
      set {
        gachaTimesLimit_ = value;
      }
    }

    /// <summary>Field number for the "gacha_sort_id" field.</summary>
    public const int GachaSortIdFieldNumber = 9;
    private uint gachaSortId_;
    /// <summary>
    /// Unk3300_DBFMKAMNPCL
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GachaSortId {
      get { return gachaSortId_; }
      set {
        gachaSortId_ = value;
      }
    }

    /// <summary>Field number for the "wish_item_id" field.</summary>
    public const int WishItemIdFieldNumber = 6;
    private uint wishItemId_;
    /// <summary>
    /// Unk3300_DDBOLMGHEKN
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint WishItemId {
      get { return wishItemId_; }
      set {
        wishItemId_ = value;
      }
    }

    /// <summary>Field number for the "is_new_wish" field.</summary>
    public const int IsNewWishFieldNumber = 967;
    private bool isNewWish_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsNewWish {
      get { return isNewWish_; }
      set {
        isNewWish_ = value;
      }
    }

    /// <summary>Field number for the "wish_progress" field.</summary>
    public const int WishProgressFieldNumber = 12;
    private uint wishProgress_;
    /// <summary>
    /// Unk3300_JLBFLPEMAPP
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint WishProgress {
      get { return wishProgress_; }
      set {
        wishProgress_ = value;
      }
    }

    /// <summary>Field number for the "wish_max_progress" field.</summary>
    public const int WishMaxProgressFieldNumber = 1580;
    private uint wishMaxProgress_;
    /// <summary>
    /// Unk3300_KEIJFMKAKDH
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint WishMaxProgress {
      get { return wishMaxProgress_; }
      set {
        wishMaxProgress_ = value;
      }
    }

    /// <summary>Field number for the "gacha_record_url_oversea" field.</summary>
    public const int GachaRecordUrlOverseaFieldNumber = 1259;
    private string gachaRecordUrlOversea_ = "";
    /// <summary>
    /// Unk3300_ODFKNFOMAGE
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GachaRecordUrlOversea {
      get { return gachaRecordUrlOversea_; }
      set {
        gachaRecordUrlOversea_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gacha_up_info_list" field.</summary>
    public const int GachaUpInfoListFieldNumber = 1585;
    private static readonly pb::FieldCodec<global::Weedwacker.Shared.Network.Proto.GachaUpInfo> _repeated_gachaUpInfoList_codec
        = pb::FieldCodec.ForMessage(12682, global::Weedwacker.Shared.Network.Proto.GachaUpInfo.Parser);
    private readonly pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.GachaUpInfo> gachaUpInfoList_ = new pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.GachaUpInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.GachaUpInfo> GachaUpInfoList {
      get { return gachaUpInfoList_; }
    }

    /// <summary>Field number for the "Unk3300_PLFMMOFNGAG" field.</summary>
    public const int Unk3300PLFMMOFNGAGFieldNumber = 3;
    private uint unk3300PLFMMOFNGAG_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Unk3300PLFMMOFNGAG {
      get { return unk3300PLFMMOFNGAG_; }
      set {
        unk3300PLFMMOFNGAG_ = value;
      }
    }

    /// <summary>Field number for the "title_textmap" field.</summary>
    public const int TitleTextmapFieldNumber = 11;
    private string titleTextmap_ = "";
    /// <summary>
    /// Unk3300_OFOHDLDFCLF
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TitleTextmap {
      get { return titleTextmap_; }
      set {
        titleTextmap_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GachaInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GachaInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CostItemId != other.CostItemId) return false;
      if (GachaType != other.GachaType) return false;
      if (CostItemNum != other.CostItemNum) return false;
      if (GachaPrefabPath != other.GachaPrefabPath) return false;
      if (GachaPreviewPrefabPath != other.GachaPreviewPrefabPath) return false;
      if (GachaProbUrl != other.GachaProbUrl) return false;
      if (BeginTime != other.BeginTime) return false;
      if (ScheduleId != other.ScheduleId) return false;
      if(!displayUp5ItemList_.Equals(other.displayUp5ItemList_)) return false;
      if (TenCostItemId != other.TenCostItemId) return false;
      if (GachaProbUrlOversea != other.GachaProbUrlOversea) return false;
      if (GachaRecordUrl != other.GachaRecordUrl) return false;
      if (TenCostItemNum != other.TenCostItemNum) return false;
      if (EndTime != other.EndTime) return false;
      if(!displayUp4ItemList_.Equals(other.displayUp4ItemList_)) return false;
      if (LeftGachaTimes != other.LeftGachaTimes) return false;
      if (GachaTimesLimit != other.GachaTimesLimit) return false;
      if (GachaSortId != other.GachaSortId) return false;
      if (WishItemId != other.WishItemId) return false;
      if (IsNewWish != other.IsNewWish) return false;
      if (WishProgress != other.WishProgress) return false;
      if (WishMaxProgress != other.WishMaxProgress) return false;
      if (GachaRecordUrlOversea != other.GachaRecordUrlOversea) return false;
      if(!gachaUpInfoList_.Equals(other.gachaUpInfoList_)) return false;
      if (Unk3300PLFMMOFNGAG != other.Unk3300PLFMMOFNGAG) return false;
      if (TitleTextmap != other.TitleTextmap) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CostItemId != 0) hash ^= CostItemId.GetHashCode();
      if (GachaType != 0) hash ^= GachaType.GetHashCode();
      if (CostItemNum != 0) hash ^= CostItemNum.GetHashCode();
      if (GachaPrefabPath.Length != 0) hash ^= GachaPrefabPath.GetHashCode();
      if (GachaPreviewPrefabPath.Length != 0) hash ^= GachaPreviewPrefabPath.GetHashCode();
      if (GachaProbUrl.Length != 0) hash ^= GachaProbUrl.GetHashCode();
      if (BeginTime != 0) hash ^= BeginTime.GetHashCode();
      if (ScheduleId != 0) hash ^= ScheduleId.GetHashCode();
      hash ^= displayUp5ItemList_.GetHashCode();
      if (TenCostItemId != 0) hash ^= TenCostItemId.GetHashCode();
      if (GachaProbUrlOversea.Length != 0) hash ^= GachaProbUrlOversea.GetHashCode();
      if (GachaRecordUrl.Length != 0) hash ^= GachaRecordUrl.GetHashCode();
      if (TenCostItemNum != 0) hash ^= TenCostItemNum.GetHashCode();
      if (EndTime != 0) hash ^= EndTime.GetHashCode();
      hash ^= displayUp4ItemList_.GetHashCode();
      if (LeftGachaTimes != 0) hash ^= LeftGachaTimes.GetHashCode();
      if (GachaTimesLimit != 0) hash ^= GachaTimesLimit.GetHashCode();
      if (GachaSortId != 0) hash ^= GachaSortId.GetHashCode();
      if (WishItemId != 0) hash ^= WishItemId.GetHashCode();
      if (IsNewWish != false) hash ^= IsNewWish.GetHashCode();
      if (WishProgress != 0) hash ^= WishProgress.GetHashCode();
      if (WishMaxProgress != 0) hash ^= WishMaxProgress.GetHashCode();
      if (GachaRecordUrlOversea.Length != 0) hash ^= GachaRecordUrlOversea.GetHashCode();
      hash ^= gachaUpInfoList_.GetHashCode();
      if (Unk3300PLFMMOFNGAG != 0) hash ^= Unk3300PLFMMOFNGAG.GetHashCode();
      if (TitleTextmap.Length != 0) hash ^= TitleTextmap.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GachaProbUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(GachaProbUrl);
      }
      if (EndTime != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(EndTime);
      }
      if (Unk3300PLFMMOFNGAG != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Unk3300PLFMMOFNGAG);
      }
      if (GachaProbUrlOversea.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(GachaProbUrlOversea);
      }
      if (CostItemId != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(CostItemId);
      }
      if (WishItemId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(WishItemId);
      }
      if (GachaType != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(GachaType);
      }
      if (ScheduleId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(ScheduleId);
      }
      if (GachaSortId != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(GachaSortId);
      }
      if (TenCostItemId != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(TenCostItemId);
      }
      if (TitleTextmap.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(TitleTextmap);
      }
      if (WishProgress != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(WishProgress);
      }
      if (LeftGachaTimes != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(LeftGachaTimes);
      }
      if (BeginTime != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(BeginTime);
      }
      if (GachaPreviewPrefabPath.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(GachaPreviewPrefabPath);
      }
      if (GachaRecordUrl.Length != 0) {
        output.WriteRawTag(146, 7);
        output.WriteString(GachaRecordUrl);
      }
      if (TenCostItemNum != 0) {
        output.WriteRawTag(168, 15);
        output.WriteUInt32(TenCostItemNum);
      }
      displayUp5ItemList_.WriteTo(output, _repeated_displayUp5ItemList_codec);
      displayUp4ItemList_.WriteTo(output, _repeated_displayUp4ItemList_codec);
      if (CostItemNum != 0) {
        output.WriteRawTag(208, 59);
        output.WriteUInt32(CostItemNum);
      }
      if (IsNewWish != false) {
        output.WriteRawTag(184, 60);
        output.WriteBool(IsNewWish);
      }
      if (GachaRecordUrlOversea.Length != 0) {
        output.WriteRawTag(218, 78);
        output.WriteString(GachaRecordUrlOversea);
      }
      if (GachaTimesLimit != 0) {
        output.WriteRawTag(216, 79);
        output.WriteUInt32(GachaTimesLimit);
      }
      if (GachaPrefabPath.Length != 0) {
        output.WriteRawTag(226, 95);
        output.WriteString(GachaPrefabPath);
      }
      if (WishMaxProgress != 0) {
        output.WriteRawTag(224, 98);
        output.WriteUInt32(WishMaxProgress);
      }
      gachaUpInfoList_.WriteTo(output, _repeated_gachaUpInfoList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GachaProbUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(GachaProbUrl);
      }
      if (EndTime != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(EndTime);
      }
      if (Unk3300PLFMMOFNGAG != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Unk3300PLFMMOFNGAG);
      }
      if (GachaProbUrlOversea.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(GachaProbUrlOversea);
      }
      if (CostItemId != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(CostItemId);
      }
      if (WishItemId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(WishItemId);
      }
      if (GachaType != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(GachaType);
      }
      if (ScheduleId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(ScheduleId);
      }
      if (GachaSortId != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(GachaSortId);
      }
      if (TenCostItemId != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(TenCostItemId);
      }
      if (TitleTextmap.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(TitleTextmap);
      }
      if (WishProgress != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(WishProgress);
      }
      if (LeftGachaTimes != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(LeftGachaTimes);
      }
      if (BeginTime != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(BeginTime);
      }
      if (GachaPreviewPrefabPath.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(GachaPreviewPrefabPath);
      }
      if (GachaRecordUrl.Length != 0) {
        output.WriteRawTag(146, 7);
        output.WriteString(GachaRecordUrl);
      }
      if (TenCostItemNum != 0) {
        output.WriteRawTag(168, 15);
        output.WriteUInt32(TenCostItemNum);
      }
      displayUp5ItemList_.WriteTo(ref output, _repeated_displayUp5ItemList_codec);
      displayUp4ItemList_.WriteTo(ref output, _repeated_displayUp4ItemList_codec);
      if (CostItemNum != 0) {
        output.WriteRawTag(208, 59);
        output.WriteUInt32(CostItemNum);
      }
      if (IsNewWish != false) {
        output.WriteRawTag(184, 60);
        output.WriteBool(IsNewWish);
      }
      if (GachaRecordUrlOversea.Length != 0) {
        output.WriteRawTag(218, 78);
        output.WriteString(GachaRecordUrlOversea);
      }
      if (GachaTimesLimit != 0) {
        output.WriteRawTag(216, 79);
        output.WriteUInt32(GachaTimesLimit);
      }
      if (GachaPrefabPath.Length != 0) {
        output.WriteRawTag(226, 95);
        output.WriteString(GachaPrefabPath);
      }
      if (WishMaxProgress != 0) {
        output.WriteRawTag(224, 98);
        output.WriteUInt32(WishMaxProgress);
      }
      gachaUpInfoList_.WriteTo(ref output, _repeated_gachaUpInfoList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CostItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CostItemId);
      }
      if (GachaType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GachaType);
      }
      if (CostItemNum != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(CostItemNum);
      }
      if (GachaPrefabPath.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(GachaPrefabPath);
      }
      if (GachaPreviewPrefabPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GachaPreviewPrefabPath);
      }
      if (GachaProbUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GachaProbUrl);
      }
      if (BeginTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BeginTime);
      }
      if (ScheduleId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ScheduleId);
      }
      size += displayUp5ItemList_.CalculateSize(_repeated_displayUp5ItemList_codec);
      if (TenCostItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TenCostItemId);
      }
      if (GachaProbUrlOversea.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GachaProbUrlOversea);
      }
      if (GachaRecordUrl.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(GachaRecordUrl);
      }
      if (TenCostItemNum != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(TenCostItemNum);
      }
      if (EndTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EndTime);
      }
      size += displayUp4ItemList_.CalculateSize(_repeated_displayUp4ItemList_codec);
      if (LeftGachaTimes != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LeftGachaTimes);
      }
      if (GachaTimesLimit != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(GachaTimesLimit);
      }
      if (GachaSortId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GachaSortId);
      }
      if (WishItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(WishItemId);
      }
      if (IsNewWish != false) {
        size += 2 + 1;
      }
      if (WishProgress != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(WishProgress);
      }
      if (WishMaxProgress != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(WishMaxProgress);
      }
      if (GachaRecordUrlOversea.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(GachaRecordUrlOversea);
      }
      size += gachaUpInfoList_.CalculateSize(_repeated_gachaUpInfoList_codec);
      if (Unk3300PLFMMOFNGAG != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Unk3300PLFMMOFNGAG);
      }
      if (TitleTextmap.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TitleTextmap);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GachaInfo other) {
      if (other == null) {
        return;
      }
      if (other.CostItemId != 0) {
        CostItemId = other.CostItemId;
      }
      if (other.GachaType != 0) {
        GachaType = other.GachaType;
      }
      if (other.CostItemNum != 0) {
        CostItemNum = other.CostItemNum;
      }
      if (other.GachaPrefabPath.Length != 0) {
        GachaPrefabPath = other.GachaPrefabPath;
      }
      if (other.GachaPreviewPrefabPath.Length != 0) {
        GachaPreviewPrefabPath = other.GachaPreviewPrefabPath;
      }
      if (other.GachaProbUrl.Length != 0) {
        GachaProbUrl = other.GachaProbUrl;
      }
      if (other.BeginTime != 0) {
        BeginTime = other.BeginTime;
      }
      if (other.ScheduleId != 0) {
        ScheduleId = other.ScheduleId;
      }
      displayUp5ItemList_.Add(other.displayUp5ItemList_);
      if (other.TenCostItemId != 0) {
        TenCostItemId = other.TenCostItemId;
      }
      if (other.GachaProbUrlOversea.Length != 0) {
        GachaProbUrlOversea = other.GachaProbUrlOversea;
      }
      if (other.GachaRecordUrl.Length != 0) {
        GachaRecordUrl = other.GachaRecordUrl;
      }
      if (other.TenCostItemNum != 0) {
        TenCostItemNum = other.TenCostItemNum;
      }
      if (other.EndTime != 0) {
        EndTime = other.EndTime;
      }
      displayUp4ItemList_.Add(other.displayUp4ItemList_);
      if (other.LeftGachaTimes != 0) {
        LeftGachaTimes = other.LeftGachaTimes;
      }
      if (other.GachaTimesLimit != 0) {
        GachaTimesLimit = other.GachaTimesLimit;
      }
      if (other.GachaSortId != 0) {
        GachaSortId = other.GachaSortId;
      }
      if (other.WishItemId != 0) {
        WishItemId = other.WishItemId;
      }
      if (other.IsNewWish != false) {
        IsNewWish = other.IsNewWish;
      }
      if (other.WishProgress != 0) {
        WishProgress = other.WishProgress;
      }
      if (other.WishMaxProgress != 0) {
        WishMaxProgress = other.WishMaxProgress;
      }
      if (other.GachaRecordUrlOversea.Length != 0) {
        GachaRecordUrlOversea = other.GachaRecordUrlOversea;
      }
      gachaUpInfoList_.Add(other.gachaUpInfoList_);
      if (other.Unk3300PLFMMOFNGAG != 0) {
        Unk3300PLFMMOFNGAG = other.Unk3300PLFMMOFNGAG;
      }
      if (other.TitleTextmap.Length != 0) {
        TitleTextmap = other.TitleTextmap;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            GachaProbUrl = input.ReadString();
            break;
          }
          case 16: {
            EndTime = input.ReadUInt32();
            break;
          }
          case 24: {
            Unk3300PLFMMOFNGAG = input.ReadUInt32();
            break;
          }
          case 34: {
            GachaProbUrlOversea = input.ReadString();
            break;
          }
          case 40: {
            CostItemId = input.ReadUInt32();
            break;
          }
          case 48: {
            WishItemId = input.ReadUInt32();
            break;
          }
          case 56: {
            GachaType = input.ReadUInt32();
            break;
          }
          case 64: {
            ScheduleId = input.ReadUInt32();
            break;
          }
          case 72: {
            GachaSortId = input.ReadUInt32();
            break;
          }
          case 80: {
            TenCostItemId = input.ReadUInt32();
            break;
          }
          case 90: {
            TitleTextmap = input.ReadString();
            break;
          }
          case 96: {
            WishProgress = input.ReadUInt32();
            break;
          }
          case 104: {
            LeftGachaTimes = input.ReadUInt32();
            break;
          }
          case 112: {
            BeginTime = input.ReadUInt32();
            break;
          }
          case 122: {
            GachaPreviewPrefabPath = input.ReadString();
            break;
          }
          case 914: {
            GachaRecordUrl = input.ReadString();
            break;
          }
          case 1960: {
            TenCostItemNum = input.ReadUInt32();
            break;
          }
          case 3810:
          case 3808: {
            displayUp5ItemList_.AddEntriesFrom(input, _repeated_displayUp5ItemList_codec);
            break;
          }
          case 4322:
          case 4320: {
            displayUp4ItemList_.AddEntriesFrom(input, _repeated_displayUp4ItemList_codec);
            break;
          }
          case 7632: {
            CostItemNum = input.ReadUInt32();
            break;
          }
          case 7736: {
            IsNewWish = input.ReadBool();
            break;
          }
          case 10074: {
            GachaRecordUrlOversea = input.ReadString();
            break;
          }
          case 10200: {
            GachaTimesLimit = input.ReadUInt32();
            break;
          }
          case 12258: {
            GachaPrefabPath = input.ReadString();
            break;
          }
          case 12640: {
            WishMaxProgress = input.ReadUInt32();
            break;
          }
          case 12682: {
            gachaUpInfoList_.AddEntriesFrom(input, _repeated_gachaUpInfoList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            GachaProbUrl = input.ReadString();
            break;
          }
          case 16: {
            EndTime = input.ReadUInt32();
            break;
          }
          case 24: {
            Unk3300PLFMMOFNGAG = input.ReadUInt32();
            break;
          }
          case 34: {
            GachaProbUrlOversea = input.ReadString();
            break;
          }
          case 40: {
            CostItemId = input.ReadUInt32();
            break;
          }
          case 48: {
            WishItemId = input.ReadUInt32();
            break;
          }
          case 56: {
            GachaType = input.ReadUInt32();
            break;
          }
          case 64: {
            ScheduleId = input.ReadUInt32();
            break;
          }
          case 72: {
            GachaSortId = input.ReadUInt32();
            break;
          }
          case 80: {
            TenCostItemId = input.ReadUInt32();
            break;
          }
          case 90: {
            TitleTextmap = input.ReadString();
            break;
          }
          case 96: {
            WishProgress = input.ReadUInt32();
            break;
          }
          case 104: {
            LeftGachaTimes = input.ReadUInt32();
            break;
          }
          case 112: {
            BeginTime = input.ReadUInt32();
            break;
          }
          case 122: {
            GachaPreviewPrefabPath = input.ReadString();
            break;
          }
          case 914: {
            GachaRecordUrl = input.ReadString();
            break;
          }
          case 1960: {
            TenCostItemNum = input.ReadUInt32();
            break;
          }
          case 3810:
          case 3808: {
            displayUp5ItemList_.AddEntriesFrom(ref input, _repeated_displayUp5ItemList_codec);
            break;
          }
          case 4322:
          case 4320: {
            displayUp4ItemList_.AddEntriesFrom(ref input, _repeated_displayUp4ItemList_codec);
            break;
          }
          case 7632: {
            CostItemNum = input.ReadUInt32();
            break;
          }
          case 7736: {
            IsNewWish = input.ReadBool();
            break;
          }
          case 10074: {
            GachaRecordUrlOversea = input.ReadString();
            break;
          }
          case 10200: {
            GachaTimesLimit = input.ReadUInt32();
            break;
          }
          case 12258: {
            GachaPrefabPath = input.ReadString();
            break;
          }
          case 12640: {
            WishMaxProgress = input.ReadUInt32();
            break;
          }
          case 12682: {
            gachaUpInfoList_.AddEntriesFrom(ref input, _repeated_gachaUpInfoList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
