// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: HomeMarkPointSceneData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from HomeMarkPointSceneData.proto</summary>
  public static partial class HomeMarkPointSceneDataReflection {

    #region Descriptor
    /// <summary>File descriptor for HomeMarkPointSceneData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HomeMarkPointSceneDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxIb21lTWFya1BvaW50U2NlbmVEYXRhLnByb3RvEh9XZWVkd2Fja2VyLlNo",
            "YXJlZC5OZXR3b3JrLlByb3RvGiBIb21lTWFya1BvaW50RnVybml0dXJlRGF0",
            "YS5wcm90bxoMVmVjdG9yLnByb3RvIpwCChZIb21lTWFya1BvaW50U2NlbmVE",
            "YXRhEkIKEXRlYXBvdF9zcGlyaXRfcG9zGAkgASgLMicuV2VlZHdhY2tlci5T",
            "aGFyZWQuTmV0d29yay5Qcm90by5WZWN0b3ISEAoIc2NlbmVfaWQYBiABKA0S",
            "RAoTVW5rMzMwMF9IRk5PSU5HUE1KUBgLIAEoCzInLldlZWR3YWNrZXIuU2hh",
            "cmVkLk5ldHdvcmsuUHJvdG8uVmVjdG9yEhEKCW1vZHVsZV9pZBgIIAEoDRJT",
            "Cg5mdXJuaXR1cmVfbGlzdBgNIAMoCzI7LldlZWR3YWNrZXIuU2hhcmVkLk5l",
            "dHdvcmsuUHJvdG8uSG9tZU1hcmtQb2ludEZ1cm5pdHVyZURhdGFiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Weedwacker.Shared.Network.Proto.HomeMarkPointFurnitureDataReflection.Descriptor, global::Weedwacker.Shared.Network.Proto.VectorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.HomeMarkPointSceneData), global::Weedwacker.Shared.Network.Proto.HomeMarkPointSceneData.Parser, new[]{ "TeapotSpiritPos", "SceneId", "Unk3300HFNOINGPMJP", "ModuleId", "FurnitureList" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class HomeMarkPointSceneData : pb::IMessage<HomeMarkPointSceneData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HomeMarkPointSceneData> _parser = new pb::MessageParser<HomeMarkPointSceneData>(() => new HomeMarkPointSceneData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HomeMarkPointSceneData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.HomeMarkPointSceneDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomeMarkPointSceneData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomeMarkPointSceneData(HomeMarkPointSceneData other) : this() {
      teapotSpiritPos_ = other.teapotSpiritPos_ != null ? other.teapotSpiritPos_.Clone() : null;
      sceneId_ = other.sceneId_;
      unk3300HFNOINGPMJP_ = other.unk3300HFNOINGPMJP_ != null ? other.unk3300HFNOINGPMJP_.Clone() : null;
      moduleId_ = other.moduleId_;
      furnitureList_ = other.furnitureList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomeMarkPointSceneData Clone() {
      return new HomeMarkPointSceneData(this);
    }

    /// <summary>Field number for the "teapot_spirit_pos" field.</summary>
    public const int TeapotSpiritPosFieldNumber = 9;
    private global::Weedwacker.Shared.Network.Proto.Vector teapotSpiritPos_;
    /// <summary>
    /// Unk3300_ONJJJEPFKJI
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.Vector TeapotSpiritPos {
      get { return teapotSpiritPos_; }
      set {
        teapotSpiritPos_ = value;
      }
    }

    /// <summary>Field number for the "scene_id" field.</summary>
    public const int SceneIdFieldNumber = 6;
    private uint sceneId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SceneId {
      get { return sceneId_; }
      set {
        sceneId_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_HFNOINGPMJP" field.</summary>
    public const int Unk3300HFNOINGPMJPFieldNumber = 11;
    private global::Weedwacker.Shared.Network.Proto.Vector unk3300HFNOINGPMJP_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.Vector Unk3300HFNOINGPMJP {
      get { return unk3300HFNOINGPMJP_; }
      set {
        unk3300HFNOINGPMJP_ = value;
      }
    }

    /// <summary>Field number for the "module_id" field.</summary>
    public const int ModuleIdFieldNumber = 8;
    private uint moduleId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ModuleId {
      get { return moduleId_; }
      set {
        moduleId_ = value;
      }
    }

    /// <summary>Field number for the "furniture_list" field.</summary>
    public const int FurnitureListFieldNumber = 13;
    private static readonly pb::FieldCodec<global::Weedwacker.Shared.Network.Proto.HomeMarkPointFurnitureData> _repeated_furnitureList_codec
        = pb::FieldCodec.ForMessage(106, global::Weedwacker.Shared.Network.Proto.HomeMarkPointFurnitureData.Parser);
    private readonly pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeMarkPointFurnitureData> furnitureList_ = new pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeMarkPointFurnitureData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeMarkPointFurnitureData> FurnitureList {
      get { return furnitureList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HomeMarkPointSceneData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HomeMarkPointSceneData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(TeapotSpiritPos, other.TeapotSpiritPos)) return false;
      if (SceneId != other.SceneId) return false;
      if (!object.Equals(Unk3300HFNOINGPMJP, other.Unk3300HFNOINGPMJP)) return false;
      if (ModuleId != other.ModuleId) return false;
      if(!furnitureList_.Equals(other.furnitureList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (teapotSpiritPos_ != null) hash ^= TeapotSpiritPos.GetHashCode();
      if (SceneId != 0) hash ^= SceneId.GetHashCode();
      if (unk3300HFNOINGPMJP_ != null) hash ^= Unk3300HFNOINGPMJP.GetHashCode();
      if (ModuleId != 0) hash ^= ModuleId.GetHashCode();
      hash ^= furnitureList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SceneId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(SceneId);
      }
      if (ModuleId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(ModuleId);
      }
      if (teapotSpiritPos_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(TeapotSpiritPos);
      }
      if (unk3300HFNOINGPMJP_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(Unk3300HFNOINGPMJP);
      }
      furnitureList_.WriteTo(output, _repeated_furnitureList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SceneId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(SceneId);
      }
      if (ModuleId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(ModuleId);
      }
      if (teapotSpiritPos_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(TeapotSpiritPos);
      }
      if (unk3300HFNOINGPMJP_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(Unk3300HFNOINGPMJP);
      }
      furnitureList_.WriteTo(ref output, _repeated_furnitureList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (teapotSpiritPos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TeapotSpiritPos);
      }
      if (SceneId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SceneId);
      }
      if (unk3300HFNOINGPMJP_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Unk3300HFNOINGPMJP);
      }
      if (ModuleId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ModuleId);
      }
      size += furnitureList_.CalculateSize(_repeated_furnitureList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HomeMarkPointSceneData other) {
      if (other == null) {
        return;
      }
      if (other.teapotSpiritPos_ != null) {
        if (teapotSpiritPos_ == null) {
          TeapotSpiritPos = new global::Weedwacker.Shared.Network.Proto.Vector();
        }
        TeapotSpiritPos.MergeFrom(other.TeapotSpiritPos);
      }
      if (other.SceneId != 0) {
        SceneId = other.SceneId;
      }
      if (other.unk3300HFNOINGPMJP_ != null) {
        if (unk3300HFNOINGPMJP_ == null) {
          Unk3300HFNOINGPMJP = new global::Weedwacker.Shared.Network.Proto.Vector();
        }
        Unk3300HFNOINGPMJP.MergeFrom(other.Unk3300HFNOINGPMJP);
      }
      if (other.ModuleId != 0) {
        ModuleId = other.ModuleId;
      }
      furnitureList_.Add(other.furnitureList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 48: {
            SceneId = input.ReadUInt32();
            break;
          }
          case 64: {
            ModuleId = input.ReadUInt32();
            break;
          }
          case 74: {
            if (teapotSpiritPos_ == null) {
              TeapotSpiritPos = new global::Weedwacker.Shared.Network.Proto.Vector();
            }
            input.ReadMessage(TeapotSpiritPos);
            break;
          }
          case 90: {
            if (unk3300HFNOINGPMJP_ == null) {
              Unk3300HFNOINGPMJP = new global::Weedwacker.Shared.Network.Proto.Vector();
            }
            input.ReadMessage(Unk3300HFNOINGPMJP);
            break;
          }
          case 106: {
            furnitureList_.AddEntriesFrom(input, _repeated_furnitureList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 48: {
            SceneId = input.ReadUInt32();
            break;
          }
          case 64: {
            ModuleId = input.ReadUInt32();
            break;
          }
          case 74: {
            if (teapotSpiritPos_ == null) {
              TeapotSpiritPos = new global::Weedwacker.Shared.Network.Proto.Vector();
            }
            input.ReadMessage(TeapotSpiritPos);
            break;
          }
          case 90: {
            if (unk3300HFNOINGPMJP_ == null) {
              Unk3300HFNOINGPMJP = new global::Weedwacker.Shared.Network.Proto.Vector();
            }
            input.ReadMessage(Unk3300HFNOINGPMJP);
            break;
          }
          case 106: {
            furnitureList_.AddEntriesFrom(ref input, _repeated_furnitureList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
