// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MusicGameSearchBeatmapRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from MusicGameSearchBeatmapRsp.proto</summary>
  public static partial class MusicGameSearchBeatmapRspReflection {

    #region Descriptor
    /// <summary>File descriptor for MusicGameSearchBeatmapRsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MusicGameSearchBeatmapRspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9NdXNpY0dhbWVTZWFyY2hCZWF0bWFwUnNwLnByb3RvEh9XZWVkd2Fja2Vy",
            "LlNoYXJlZC5OZXR3b3JrLlByb3RvGhRNdXNpY0JyaWVmSW5mby5wcm90bxob",
            "TXVzaWNHYW1lVW5rbm93bjFFbnVtLnByb3RvIu8BChlNdXNpY0dhbWVTZWFy",
            "Y2hCZWF0bWFwUnNwEg8KB3JldGNvZGUYCSABKAUSTQoNdW5rbm93bl9lbnVt",
            "MRgDIAEoDjI2LldlZWR3YWNrZXIuU2hhcmVkLk5ldHdvcmsuUHJvdG8uTXVz",
            "aWNHYW1lVW5rbm93bjFFbnVtEhYKDm11c2ljX3NoYXJlX2lkGAQgASgEEksK",
            "EG11c2ljX2JyaWVmX2luZm8YCyABKAsyLy5XZWVkd2Fja2VyLlNoYXJlZC5O",
            "ZXR3b3JrLlByb3RvLk11c2ljQnJpZWZJbmZvSABCDQoLRUxCRUlGR0RCTU1i",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Weedwacker.Shared.Network.Proto.MusicBriefInfoReflection.Descriptor, global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1EnumReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.MusicGameSearchBeatmapRsp), global::Weedwacker.Shared.Network.Proto.MusicGameSearchBeatmapRsp.Parser, new[]{ "Retcode", "UnknownEnum1", "MusicShareId", "MusicBriefInfo" }, new[]{ "ELBEIFGDBMM" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// CmdId: 6304
  /// EnetChannelId: 0
  /// EnetIsReliable: true
  /// </summary>
  public sealed partial class MusicGameSearchBeatmapRsp : pb::IMessage<MusicGameSearchBeatmapRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MusicGameSearchBeatmapRsp> _parser = new pb::MessageParser<MusicGameSearchBeatmapRsp>(() => new MusicGameSearchBeatmapRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MusicGameSearchBeatmapRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.MusicGameSearchBeatmapRspReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MusicGameSearchBeatmapRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MusicGameSearchBeatmapRsp(MusicGameSearchBeatmapRsp other) : this() {
      retcode_ = other.retcode_;
      unknownEnum1_ = other.unknownEnum1_;
      musicShareId_ = other.musicShareId_;
      switch (other.ELBEIFGDBMMCase) {
        case ELBEIFGDBMMOneofCase.MusicBriefInfo:
          MusicBriefInfo = other.MusicBriefInfo.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MusicGameSearchBeatmapRsp Clone() {
      return new MusicGameSearchBeatmapRsp(this);
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 9;
    private int retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    /// <summary>Field number for the "unknown_enum1" field.</summary>
    public const int UnknownEnum1FieldNumber = 3;
    private global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum unknownEnum1_ = global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum UnknownEnum1 {
      get { return unknownEnum1_; }
      set {
        unknownEnum1_ = value;
      }
    }

    /// <summary>Field number for the "music_share_id" field.</summary>
    public const int MusicShareIdFieldNumber = 4;
    private ulong musicShareId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong MusicShareId {
      get { return musicShareId_; }
      set {
        musicShareId_ = value;
      }
    }

    /// <summary>Field number for the "music_brief_info" field.</summary>
    public const int MusicBriefInfoFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.MusicBriefInfo MusicBriefInfo {
      get { return eLBEIFGDBMMCase_ == ELBEIFGDBMMOneofCase.MusicBriefInfo ? (global::Weedwacker.Shared.Network.Proto.MusicBriefInfo) eLBEIFGDBMM_ : null; }
      set {
        eLBEIFGDBMM_ = value;
        eLBEIFGDBMMCase_ = value == null ? ELBEIFGDBMMOneofCase.None : ELBEIFGDBMMOneofCase.MusicBriefInfo;
      }
    }

    private object eLBEIFGDBMM_;
    /// <summary>Enum of possible cases for the "ELBEIFGDBMM" oneof.</summary>
    public enum ELBEIFGDBMMOneofCase {
      None = 0,
      MusicBriefInfo = 11,
    }
    private ELBEIFGDBMMOneofCase eLBEIFGDBMMCase_ = ELBEIFGDBMMOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ELBEIFGDBMMOneofCase ELBEIFGDBMMCase {
      get { return eLBEIFGDBMMCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearELBEIFGDBMM() {
      eLBEIFGDBMMCase_ = ELBEIFGDBMMOneofCase.None;
      eLBEIFGDBMM_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MusicGameSearchBeatmapRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MusicGameSearchBeatmapRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Retcode != other.Retcode) return false;
      if (UnknownEnum1 != other.UnknownEnum1) return false;
      if (MusicShareId != other.MusicShareId) return false;
      if (!object.Equals(MusicBriefInfo, other.MusicBriefInfo)) return false;
      if (ELBEIFGDBMMCase != other.ELBEIFGDBMMCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      if (UnknownEnum1 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None) hash ^= UnknownEnum1.GetHashCode();
      if (MusicShareId != 0UL) hash ^= MusicShareId.GetHashCode();
      if (eLBEIFGDBMMCase_ == ELBEIFGDBMMOneofCase.MusicBriefInfo) hash ^= MusicBriefInfo.GetHashCode();
      hash ^= (int) eLBEIFGDBMMCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UnknownEnum1 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None) {
        output.WriteRawTag(24);
        output.WriteEnum((int) UnknownEnum1);
      }
      if (MusicShareId != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(MusicShareId);
      }
      if (Retcode != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Retcode);
      }
      if (eLBEIFGDBMMCase_ == ELBEIFGDBMMOneofCase.MusicBriefInfo) {
        output.WriteRawTag(90);
        output.WriteMessage(MusicBriefInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UnknownEnum1 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None) {
        output.WriteRawTag(24);
        output.WriteEnum((int) UnknownEnum1);
      }
      if (MusicShareId != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(MusicShareId);
      }
      if (Retcode != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Retcode);
      }
      if (eLBEIFGDBMMCase_ == ELBEIFGDBMMOneofCase.MusicBriefInfo) {
        output.WriteRawTag(90);
        output.WriteMessage(MusicBriefInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Retcode);
      }
      if (UnknownEnum1 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UnknownEnum1);
      }
      if (MusicShareId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MusicShareId);
      }
      if (eLBEIFGDBMMCase_ == ELBEIFGDBMMOneofCase.MusicBriefInfo) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MusicBriefInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MusicGameSearchBeatmapRsp other) {
      if (other == null) {
        return;
      }
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      if (other.UnknownEnum1 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None) {
        UnknownEnum1 = other.UnknownEnum1;
      }
      if (other.MusicShareId != 0UL) {
        MusicShareId = other.MusicShareId;
      }
      switch (other.ELBEIFGDBMMCase) {
        case ELBEIFGDBMMOneofCase.MusicBriefInfo:
          if (MusicBriefInfo == null) {
            MusicBriefInfo = new global::Weedwacker.Shared.Network.Proto.MusicBriefInfo();
          }
          MusicBriefInfo.MergeFrom(other.MusicBriefInfo);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 24: {
            UnknownEnum1 = (global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum) input.ReadEnum();
            break;
          }
          case 32: {
            MusicShareId = input.ReadUInt64();
            break;
          }
          case 72: {
            Retcode = input.ReadInt32();
            break;
          }
          case 90: {
            global::Weedwacker.Shared.Network.Proto.MusicBriefInfo subBuilder = new global::Weedwacker.Shared.Network.Proto.MusicBriefInfo();
            if (eLBEIFGDBMMCase_ == ELBEIFGDBMMOneofCase.MusicBriefInfo) {
              subBuilder.MergeFrom(MusicBriefInfo);
            }
            input.ReadMessage(subBuilder);
            MusicBriefInfo = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 24: {
            UnknownEnum1 = (global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum) input.ReadEnum();
            break;
          }
          case 32: {
            MusicShareId = input.ReadUInt64();
            break;
          }
          case 72: {
            Retcode = input.ReadInt32();
            break;
          }
          case 90: {
            global::Weedwacker.Shared.Network.Proto.MusicBriefInfo subBuilder = new global::Weedwacker.Shared.Network.Proto.MusicBriefInfo();
            if (eLBEIFGDBMMCase_ == ELBEIFGDBMMOneofCase.MusicBriefInfo) {
              subBuilder.MergeFrom(MusicBriefInfo);
            }
            input.ReadMessage(subBuilder);
            MusicBriefInfo = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
