// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MusicGameGetBeatmapReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from MusicGameGetBeatmapReq.proto</summary>
  public static partial class MusicGameGetBeatmapReqReflection {

    #region Descriptor
    /// <summary>File descriptor for MusicGameGetBeatmapReq.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MusicGameGetBeatmapReqReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxNdXNpY0dhbWVHZXRCZWF0bWFwUmVxLnByb3RvEh9XZWVkd2Fja2VyLlNo",
            "YXJlZC5OZXR3b3JrLlByb3RvGhtNdXNpY0dhbWVVbmtub3duMkVudW0ucHJv",
            "dG8aIE11c2ljR2FtZUdldEJlYXRtYXBSZXFUeXBlLnByb3RvGhtNdXNpY0dh",
            "bWVVbmtub3duMUVudW0ucHJvdG8isgIKFk11c2ljR2FtZUdldEJlYXRtYXBS",
            "ZXESTQoNdW5rbm93bl9lbnVtMRgBIAEoDjI2LldlZWR3YWNrZXIuU2hhcmVk",
            "Lk5ldHdvcmsuUHJvdG8uTXVzaWNHYW1lVW5rbm93bjFFbnVtEhYKDm11c2lj",
            "X3NoYXJlX2lkGAogASgEEk0KDXVua25vd25fZW51bTIYDCABKA4yNi5XZWVk",
            "d2Fja2VyLlNoYXJlZC5OZXR3b3JrLlByb3RvLk11c2ljR2FtZVVua25vd24y",
            "RW51bRITCgtDREZPR0dETEtOQRgPIAEoCBJNCghyZXFfdHlwZRgLIAEoDjI7",
            "LldlZWR3YWNrZXIuU2hhcmVkLk5ldHdvcmsuUHJvdG8uTXVzaWNHYW1lR2V0",
            "QmVhdG1hcFJlcVR5cGViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Weedwacker.Shared.Network.Proto.MusicGameUnknown2EnumReflection.Descriptor, global::Weedwacker.Shared.Network.Proto.MusicGameGetBeatmapReqTypeReflection.Descriptor, global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1EnumReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.MusicGameGetBeatmapReq), global::Weedwacker.Shared.Network.Proto.MusicGameGetBeatmapReq.Parser, new[]{ "UnknownEnum1", "MusicShareId", "UnknownEnum2", "CDFOGGDLKNA", "ReqType" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// CmdId: 6318
  /// EnetChannelId: 0
  /// EnetIsReliable: true
  /// IsAllowClient: true
  /// </summary>
  public sealed partial class MusicGameGetBeatmapReq : pb::IMessage<MusicGameGetBeatmapReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MusicGameGetBeatmapReq> _parser = new pb::MessageParser<MusicGameGetBeatmapReq>(() => new MusicGameGetBeatmapReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MusicGameGetBeatmapReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.MusicGameGetBeatmapReqReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MusicGameGetBeatmapReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MusicGameGetBeatmapReq(MusicGameGetBeatmapReq other) : this() {
      unknownEnum1_ = other.unknownEnum1_;
      musicShareId_ = other.musicShareId_;
      unknownEnum2_ = other.unknownEnum2_;
      cDFOGGDLKNA_ = other.cDFOGGDLKNA_;
      reqType_ = other.reqType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MusicGameGetBeatmapReq Clone() {
      return new MusicGameGetBeatmapReq(this);
    }

    /// <summary>Field number for the "unknown_enum1" field.</summary>
    public const int UnknownEnum1FieldNumber = 1;
    private global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum unknownEnum1_ = global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum UnknownEnum1 {
      get { return unknownEnum1_; }
      set {
        unknownEnum1_ = value;
      }
    }

    /// <summary>Field number for the "music_share_id" field.</summary>
    public const int MusicShareIdFieldNumber = 10;
    private ulong musicShareId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong MusicShareId {
      get { return musicShareId_; }
      set {
        musicShareId_ = value;
      }
    }

    /// <summary>Field number for the "unknown_enum2" field.</summary>
    public const int UnknownEnum2FieldNumber = 12;
    private global::Weedwacker.Shared.Network.Proto.MusicGameUnknown2Enum unknownEnum2_ = global::Weedwacker.Shared.Network.Proto.MusicGameUnknown2Enum.U1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.MusicGameUnknown2Enum UnknownEnum2 {
      get { return unknownEnum2_; }
      set {
        unknownEnum2_ = value;
      }
    }

    /// <summary>Field number for the "CDFOGGDLKNA" field.</summary>
    public const int CDFOGGDLKNAFieldNumber = 15;
    private bool cDFOGGDLKNA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CDFOGGDLKNA {
      get { return cDFOGGDLKNA_; }
      set {
        cDFOGGDLKNA_ = value;
      }
    }

    /// <summary>Field number for the "req_type" field.</summary>
    public const int ReqTypeFieldNumber = 11;
    private global::Weedwacker.Shared.Network.Proto.MusicGameGetBeatmapReqType reqType_ = global::Weedwacker.Shared.Network.Proto.MusicGameGetBeatmapReqType.U1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.MusicGameGetBeatmapReqType ReqType {
      get { return reqType_; }
      set {
        reqType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MusicGameGetBeatmapReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MusicGameGetBeatmapReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnknownEnum1 != other.UnknownEnum1) return false;
      if (MusicShareId != other.MusicShareId) return false;
      if (UnknownEnum2 != other.UnknownEnum2) return false;
      if (CDFOGGDLKNA != other.CDFOGGDLKNA) return false;
      if (ReqType != other.ReqType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UnknownEnum1 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None) hash ^= UnknownEnum1.GetHashCode();
      if (MusicShareId != 0UL) hash ^= MusicShareId.GetHashCode();
      if (UnknownEnum2 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown2Enum.U1) hash ^= UnknownEnum2.GetHashCode();
      if (CDFOGGDLKNA != false) hash ^= CDFOGGDLKNA.GetHashCode();
      if (ReqType != global::Weedwacker.Shared.Network.Proto.MusicGameGetBeatmapReqType.U1) hash ^= ReqType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UnknownEnum1 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) UnknownEnum1);
      }
      if (MusicShareId != 0UL) {
        output.WriteRawTag(80);
        output.WriteUInt64(MusicShareId);
      }
      if (ReqType != global::Weedwacker.Shared.Network.Proto.MusicGameGetBeatmapReqType.U1) {
        output.WriteRawTag(88);
        output.WriteEnum((int) ReqType);
      }
      if (UnknownEnum2 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown2Enum.U1) {
        output.WriteRawTag(96);
        output.WriteEnum((int) UnknownEnum2);
      }
      if (CDFOGGDLKNA != false) {
        output.WriteRawTag(120);
        output.WriteBool(CDFOGGDLKNA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UnknownEnum1 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) UnknownEnum1);
      }
      if (MusicShareId != 0UL) {
        output.WriteRawTag(80);
        output.WriteUInt64(MusicShareId);
      }
      if (ReqType != global::Weedwacker.Shared.Network.Proto.MusicGameGetBeatmapReqType.U1) {
        output.WriteRawTag(88);
        output.WriteEnum((int) ReqType);
      }
      if (UnknownEnum2 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown2Enum.U1) {
        output.WriteRawTag(96);
        output.WriteEnum((int) UnknownEnum2);
      }
      if (CDFOGGDLKNA != false) {
        output.WriteRawTag(120);
        output.WriteBool(CDFOGGDLKNA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UnknownEnum1 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UnknownEnum1);
      }
      if (MusicShareId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MusicShareId);
      }
      if (UnknownEnum2 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown2Enum.U1) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UnknownEnum2);
      }
      if (CDFOGGDLKNA != false) {
        size += 1 + 1;
      }
      if (ReqType != global::Weedwacker.Shared.Network.Proto.MusicGameGetBeatmapReqType.U1) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ReqType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MusicGameGetBeatmapReq other) {
      if (other == null) {
        return;
      }
      if (other.UnknownEnum1 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None) {
        UnknownEnum1 = other.UnknownEnum1;
      }
      if (other.MusicShareId != 0UL) {
        MusicShareId = other.MusicShareId;
      }
      if (other.UnknownEnum2 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown2Enum.U1) {
        UnknownEnum2 = other.UnknownEnum2;
      }
      if (other.CDFOGGDLKNA != false) {
        CDFOGGDLKNA = other.CDFOGGDLKNA;
      }
      if (other.ReqType != global::Weedwacker.Shared.Network.Proto.MusicGameGetBeatmapReqType.U1) {
        ReqType = other.ReqType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            UnknownEnum1 = (global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum) input.ReadEnum();
            break;
          }
          case 80: {
            MusicShareId = input.ReadUInt64();
            break;
          }
          case 88: {
            ReqType = (global::Weedwacker.Shared.Network.Proto.MusicGameGetBeatmapReqType) input.ReadEnum();
            break;
          }
          case 96: {
            UnknownEnum2 = (global::Weedwacker.Shared.Network.Proto.MusicGameUnknown2Enum) input.ReadEnum();
            break;
          }
          case 120: {
            CDFOGGDLKNA = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            UnknownEnum1 = (global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum) input.ReadEnum();
            break;
          }
          case 80: {
            MusicShareId = input.ReadUInt64();
            break;
          }
          case 88: {
            ReqType = (global::Weedwacker.Shared.Network.Proto.MusicGameGetBeatmapReqType) input.ReadEnum();
            break;
          }
          case 96: {
            UnknownEnum2 = (global::Weedwacker.Shared.Network.Proto.MusicGameUnknown2Enum) input.ReadEnum();
            break;
          }
          case 120: {
            CDFOGGDLKNA = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
