// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MusicGameGetBeatmapReqType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from MusicGameGetBeatmapReqType.proto</summary>
  public static partial class MusicGameGetBeatmapReqTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for MusicGameGetBeatmapReqType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MusicGameGetBeatmapReqTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBNdXNpY0dhbWVHZXRCZWF0bWFwUmVxVHlwZS5wcm90bxIfV2VlZHdhY2tl",
            "ci5TaGFyZWQuTmV0d29yay5Qcm90byrLAQoaTXVzaWNHYW1lR2V0QmVhdG1h",
            "cFJlcVR5cGUSIQodTXVzaWNHYW1lR2V0QmVhdG1hcFJlcVR5cGVfdTEQABIh",
            "Ch1NdXNpY0dhbWVHZXRCZWF0bWFwUmVxVHlwZV91MhABEiEKHU11c2ljR2Ft",
            "ZUdldEJlYXRtYXBSZXFUeXBlX3UzEAISIQodTXVzaWNHYW1lR2V0QmVhdG1h",
            "cFJlcVR5cGVfdTQQAxIhCh1NdXNpY0dhbWVHZXRCZWF0bWFwUmVxVHlwZV91",
            "NRAEYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Weedwacker.Shared.Network.Proto.MusicGameGetBeatmapReqType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MusicGameGetBeatmapReqType {
    [pbr::OriginalName("MusicGameGetBeatmapReqType_u1")] U1 = 0,
    /// <summary>
    /// edit_beatmap
    /// </summary>
    [pbr::OriginalName("MusicGameGetBeatmapReqType_u2")] U2 = 1,
    /// <summary>
    /// play_others
    /// </summary>
    [pbr::OriginalName("MusicGameGetBeatmapReqType_u3")] U3 = 2,
    /// <summary>
    /// try
    /// </summary>
    [pbr::OriginalName("MusicGameGetBeatmapReqType_u4")] U4 = 3,
    [pbr::OriginalName("MusicGameGetBeatmapReqType_u5")] U5 = 4,
  }

  #endregion

}

#endregion Designer generated code
