// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MusicGameUnknown1Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from MusicGameUnknown1Enum.proto</summary>
  public static partial class MusicGameUnknown1EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for MusicGameUnknown1Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MusicGameUnknown1EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtNdXNpY0dhbWVVbmtub3duMUVudW0ucHJvdG8SH1dlZWR3YWNrZXIuU2hh",
            "cmVkLk5ldHdvcmsuUHJvdG8qVQoVTXVzaWNHYW1lVW5rbm93bjFFbnVtEh4K",
            "Gk11c2ljR2FtZVVua25vd24xRW51bV9OT05FEAASHAoYTXVzaWNHYW1lVW5r",
            "bm93bjFFbnVtX3UyEAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MusicGameUnknown1Enum {
    [pbr::OriginalName("MusicGameUnknown1Enum_NONE")] None = 0,
    [pbr::OriginalName("MusicGameUnknown1Enum_u2")] U2 = 1,
  }

  #endregion

}

#endregion Designer generated code
