// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MusicGameUnknown2Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from MusicGameUnknown2Enum.proto</summary>
  public static partial class MusicGameUnknown2EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for MusicGameUnknown2Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MusicGameUnknown2EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtNdXNpY0dhbWVVbmtub3duMkVudW0ucHJvdG8SH1dlZWR3YWNrZXIuU2hh",
            "cmVkLk5ldHdvcmsuUHJvdG8qcwoVTXVzaWNHYW1lVW5rbm93bjJFbnVtEhwK",
            "GE11c2ljR2FtZVVua25vd24yRW51bV91MRAAEh4KGk11c2ljR2FtZVVua25v",
            "d24yRW51bV9NSU5FEAESHAoYTXVzaWNHYW1lVW5rbm93bjJFbnVtX3UzEAJi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Weedwacker.Shared.Network.Proto.MusicGameUnknown2Enum), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MusicGameUnknown2Enum {
    [pbr::OriginalName("MusicGameUnknown2Enum_u1")] U1 = 0,
    [pbr::OriginalName("MusicGameUnknown2Enum_MINE")] Mine = 1,
    [pbr::OriginalName("MusicGameUnknown2Enum_u3")] U3 = 2,
  }

  #endregion

}

#endregion Designer generated code
