// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MusicGameStartToPlayOthersBeatmapRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from MusicGameStartToPlayOthersBeatmapRsp.proto</summary>
  public static partial class MusicGameStartToPlayOthersBeatmapRspReflection {

    #region Descriptor
    /// <summary>File descriptor for MusicGameStartToPlayOthersBeatmapRsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MusicGameStartToPlayOthersBeatmapRspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CipNdXNpY0dhbWVTdGFydFRvUGxheU90aGVyc0JlYXRtYXBSc3AucHJvdG8S",
            "H1dlZWR3YWNrZXIuU2hhcmVkLk5ldHdvcmsuUHJvdG8aG011c2ljR2FtZVVu",
            "a25vd24xRW51bS5wcm90byKbAQokTXVzaWNHYW1lU3RhcnRUb1BsYXlPdGhl",
            "cnNCZWF0bWFwUnNwEg8KB3JldGNvZGUYAiABKAUSTQoNdW5rbm93bl9lbnVt",
            "MRgLIAEoDjI2LldlZWR3YWNrZXIuU2hhcmVkLk5ldHdvcmsuUHJvdG8uTXVz",
            "aWNHYW1lVW5rbm93bjFFbnVtEhMKC0FNTk9ET0xOT0lNGAYgAygEYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1EnumReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.MusicGameStartToPlayOthersBeatmapRsp), global::Weedwacker.Shared.Network.Proto.MusicGameStartToPlayOthersBeatmapRsp.Parser, new[]{ "Retcode", "UnknownEnum1", "AMNODOLNOIM" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// CmdId: 6313
  /// EnetChannelId: 0
  /// EnetIsReliable: true
  /// </summary>
  public sealed partial class MusicGameStartToPlayOthersBeatmapRsp : pb::IMessage<MusicGameStartToPlayOthersBeatmapRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MusicGameStartToPlayOthersBeatmapRsp> _parser = new pb::MessageParser<MusicGameStartToPlayOthersBeatmapRsp>(() => new MusicGameStartToPlayOthersBeatmapRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MusicGameStartToPlayOthersBeatmapRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.MusicGameStartToPlayOthersBeatmapRspReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MusicGameStartToPlayOthersBeatmapRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MusicGameStartToPlayOthersBeatmapRsp(MusicGameStartToPlayOthersBeatmapRsp other) : this() {
      retcode_ = other.retcode_;
      unknownEnum1_ = other.unknownEnum1_;
      aMNODOLNOIM_ = other.aMNODOLNOIM_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MusicGameStartToPlayOthersBeatmapRsp Clone() {
      return new MusicGameStartToPlayOthersBeatmapRsp(this);
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 2;
    private int retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    /// <summary>Field number for the "unknown_enum1" field.</summary>
    public const int UnknownEnum1FieldNumber = 11;
    private global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum unknownEnum1_ = global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum UnknownEnum1 {
      get { return unknownEnum1_; }
      set {
        unknownEnum1_ = value;
      }
    }

    /// <summary>Field number for the "AMNODOLNOIM" field.</summary>
    public const int AMNODOLNOIMFieldNumber = 6;
    private static readonly pb::FieldCodec<ulong> _repeated_aMNODOLNOIM_codec
        = pb::FieldCodec.ForUInt64(50);
    private readonly pbc::RepeatedField<ulong> aMNODOLNOIM_ = new pbc::RepeatedField<ulong>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<ulong> AMNODOLNOIM {
      get { return aMNODOLNOIM_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MusicGameStartToPlayOthersBeatmapRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MusicGameStartToPlayOthersBeatmapRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Retcode != other.Retcode) return false;
      if (UnknownEnum1 != other.UnknownEnum1) return false;
      if(!aMNODOLNOIM_.Equals(other.aMNODOLNOIM_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      if (UnknownEnum1 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None) hash ^= UnknownEnum1.GetHashCode();
      hash ^= aMNODOLNOIM_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Retcode != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Retcode);
      }
      aMNODOLNOIM_.WriteTo(output, _repeated_aMNODOLNOIM_codec);
      if (UnknownEnum1 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None) {
        output.WriteRawTag(88);
        output.WriteEnum((int) UnknownEnum1);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Retcode != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Retcode);
      }
      aMNODOLNOIM_.WriteTo(ref output, _repeated_aMNODOLNOIM_codec);
      if (UnknownEnum1 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None) {
        output.WriteRawTag(88);
        output.WriteEnum((int) UnknownEnum1);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Retcode);
      }
      if (UnknownEnum1 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UnknownEnum1);
      }
      size += aMNODOLNOIM_.CalculateSize(_repeated_aMNODOLNOIM_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MusicGameStartToPlayOthersBeatmapRsp other) {
      if (other == null) {
        return;
      }
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      if (other.UnknownEnum1 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None) {
        UnknownEnum1 = other.UnknownEnum1;
      }
      aMNODOLNOIM_.Add(other.aMNODOLNOIM_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            Retcode = input.ReadInt32();
            break;
          }
          case 50:
          case 48: {
            aMNODOLNOIM_.AddEntriesFrom(input, _repeated_aMNODOLNOIM_codec);
            break;
          }
          case 88: {
            UnknownEnum1 = (global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            Retcode = input.ReadInt32();
            break;
          }
          case 50:
          case 48: {
            aMNODOLNOIM_.AddEntriesFrom(ref input, _repeated_aMNODOLNOIM_codec);
            break;
          }
          case 88: {
            UnknownEnum1 = (global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
