// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MusicGameSearchBeatmapReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from MusicGameSearchBeatmapReq.proto</summary>
  public static partial class MusicGameSearchBeatmapReqReflection {

    #region Descriptor
    /// <summary>File descriptor for MusicGameSearchBeatmapReq.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MusicGameSearchBeatmapReqReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9NdXNpY0dhbWVTZWFyY2hCZWF0bWFwUmVxLnByb3RvEh9XZWVkd2Fja2Vy",
            "LlNoYXJlZC5OZXR3b3JrLlByb3RvGhtNdXNpY0dhbWVVbmtub3duMUVudW0u",
            "cHJvdG8iggEKGU11c2ljR2FtZVNlYXJjaEJlYXRtYXBSZXESTQoNdW5rbm93",
            "bl9lbnVtMRgKIAEoDjI2LldlZWR3YWNrZXIuU2hhcmVkLk5ldHdvcmsuUHJv",
            "dG8uTXVzaWNHYW1lVW5rbm93bjFFbnVtEhYKDm11c2ljX3NoYXJlX2lkGAYg",
            "ASgEYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1EnumReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.MusicGameSearchBeatmapReq), global::Weedwacker.Shared.Network.Proto.MusicGameSearchBeatmapReq.Parser, new[]{ "UnknownEnum1", "MusicShareId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// CmdId: 6343
  /// EnetChannelId: 0
  /// EnetIsReliable: true
  /// IsAllowClient: true
  /// </summary>
  public sealed partial class MusicGameSearchBeatmapReq : pb::IMessage<MusicGameSearchBeatmapReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MusicGameSearchBeatmapReq> _parser = new pb::MessageParser<MusicGameSearchBeatmapReq>(() => new MusicGameSearchBeatmapReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MusicGameSearchBeatmapReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.MusicGameSearchBeatmapReqReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MusicGameSearchBeatmapReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MusicGameSearchBeatmapReq(MusicGameSearchBeatmapReq other) : this() {
      unknownEnum1_ = other.unknownEnum1_;
      musicShareId_ = other.musicShareId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MusicGameSearchBeatmapReq Clone() {
      return new MusicGameSearchBeatmapReq(this);
    }

    /// <summary>Field number for the "unknown_enum1" field.</summary>
    public const int UnknownEnum1FieldNumber = 10;
    private global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum unknownEnum1_ = global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum UnknownEnum1 {
      get { return unknownEnum1_; }
      set {
        unknownEnum1_ = value;
      }
    }

    /// <summary>Field number for the "music_share_id" field.</summary>
    public const int MusicShareIdFieldNumber = 6;
    private ulong musicShareId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong MusicShareId {
      get { return musicShareId_; }
      set {
        musicShareId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MusicGameSearchBeatmapReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MusicGameSearchBeatmapReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnknownEnum1 != other.UnknownEnum1) return false;
      if (MusicShareId != other.MusicShareId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UnknownEnum1 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None) hash ^= UnknownEnum1.GetHashCode();
      if (MusicShareId != 0UL) hash ^= MusicShareId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MusicShareId != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(MusicShareId);
      }
      if (UnknownEnum1 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None) {
        output.WriteRawTag(80);
        output.WriteEnum((int) UnknownEnum1);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MusicShareId != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(MusicShareId);
      }
      if (UnknownEnum1 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None) {
        output.WriteRawTag(80);
        output.WriteEnum((int) UnknownEnum1);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UnknownEnum1 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UnknownEnum1);
      }
      if (MusicShareId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MusicShareId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MusicGameSearchBeatmapReq other) {
      if (other == null) {
        return;
      }
      if (other.UnknownEnum1 != global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum.None) {
        UnknownEnum1 = other.UnknownEnum1;
      }
      if (other.MusicShareId != 0UL) {
        MusicShareId = other.MusicShareId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 48: {
            MusicShareId = input.ReadUInt64();
            break;
          }
          case 80: {
            UnknownEnum1 = (global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 48: {
            MusicShareId = input.ReadUInt64();
            break;
          }
          case 80: {
            UnknownEnum1 = (global::Weedwacker.Shared.Network.Proto.MusicGameUnknown1Enum) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
