// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PlayerApplyEnterMpReason.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from PlayerApplyEnterMpReason.proto</summary>
  public static partial class PlayerApplyEnterMpReasonReflection {

    #region Descriptor
    /// <summary>File descriptor for PlayerApplyEnterMpReason.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerApplyEnterMpReasonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5QbGF5ZXJBcHBseUVudGVyTXBSZWFzb24ucHJvdG8SH1dlZWR3YWNrZXIu",
            "U2hhcmVkLk5ldHdvcmsuUHJvdG8qzwIKGFBsYXllckFwcGx5RW50ZXJNcFJl",
            "YXNvbhIPCgtQbGF5ZXJKdWRnZRAAEhQKEFNjZW5lQ2Fubm90RW50ZXIQARIX",
            "ChNQbGF5ZXJDYW5ub3RFbnRlck1wEAISDwoLU3lzdGVtSnVkZ2UQAxIYChRB",
            "bGxvd0VudGVyUGxheWVyRnVsbBAEEhsKF1dvcmxkTGV2ZWxMb3dlclRoYW5I",
            "b3N0EAUSDwoLSG9zdEluTWF0Y2gQBhIVChFQbGF5ZXJJbkJsYWNrbGlzdBAH",
            "EhsKF1BzUGxheWVyTm90QWNjZXB0T3RoZXJzEAgSEQoNSG9zdElzQmxvY2tl",
            "ZBAJEh0KGU90aGVyRGF0YVZlcnNpb25Ob3RMYXRlc3QQChIYChREYXRhVmVy",
            "c2lvbk5vdExhdGVzdBALEhoKFlBsYXllck5vdEluUGxheWVyV29ybGQQDGIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Weedwacker.Shared.Network.Proto.PlayerApplyEnterMpReason), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum PlayerApplyEnterMpReason {
    [pbr::OriginalName("PlayerJudge")] PlayerJudge = 0,
    [pbr::OriginalName("SceneCannotEnter")] SceneCannotEnter = 1,
    [pbr::OriginalName("PlayerCannotEnterMp")] PlayerCannotEnterMp = 2,
    [pbr::OriginalName("SystemJudge")] SystemJudge = 3,
    [pbr::OriginalName("AllowEnterPlayerFull")] AllowEnterPlayerFull = 4,
    [pbr::OriginalName("WorldLevelLowerThanHost")] WorldLevelLowerThanHost = 5,
    [pbr::OriginalName("HostInMatch")] HostInMatch = 6,
    [pbr::OriginalName("PlayerInBlacklist")] PlayerInBlacklist = 7,
    [pbr::OriginalName("PsPlayerNotAcceptOthers")] PsPlayerNotAcceptOthers = 8,
    [pbr::OriginalName("HostIsBlocked")] HostIsBlocked = 9,
    [pbr::OriginalName("OtherDataVersionNotLatest")] OtherDataVersionNotLatest = 10,
    [pbr::OriginalName("DataVersionNotLatest")] DataVersionNotLatest = 11,
    [pbr::OriginalName("PlayerNotInPlayerWorld")] PlayerNotInPlayerWorld = 12,
  }

  #endregion

}

#endregion Designer generated code
