// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ShopGoodsDisableType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from ShopGoodsDisableType.proto</summary>
  public static partial class ShopGoodsDisableTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for ShopGoodsDisableType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ShopGoodsDisableTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpTaG9wR29vZHNEaXNhYmxlVHlwZS5wcm90bxIfV2VlZHdhY2tlci5TaGFy",
            "ZWQuTmV0d29yay5Qcm90byqzAQoUU2hvcEdvb2RzRGlzYWJsZVR5cGUSGwoX",
            "U0hPUF9HT09EU19ESVNBQkxFX05PTkUQABIiCh5TSE9QX0dPT0RTX0RJU0FC",
            "TEVfVEFMRU5UX0ZVTEwQARIxCi1TSE9QX0dPT0RTX0RJU0FCTEVfRlVSTklU",
            "VVJFX0ZPUk1VTEFfVU5MT0NLRUQQAhInCiNTSE9QX0dPT0RTX0RJU0FCTEVf",
            "Q09TVFVNRV9VTkxPQ0tFRBADYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Weedwacker.Shared.Network.Proto.ShopGoodsDisableType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ShopGoodsDisableType {
    [pbr::OriginalName("SHOP_GOODS_DISABLE_NONE")] ShopGoodsDisableNone = 0,
    [pbr::OriginalName("SHOP_GOODS_DISABLE_TALENT_FULL")] ShopGoodsDisableTalentFull = 1,
    [pbr::OriginalName("SHOP_GOODS_DISABLE_FURNITURE_FORMULA_UNLOCKED")] ShopGoodsDisableFurnitureFormulaUnlocked = 2,
    [pbr::OriginalName("SHOP_GOODS_DISABLE_COSTUME_UNLOCKED")] ShopGoodsDisableCostumeUnlocked = 3,
  }

  #endregion

}

#endregion Designer generated code
