// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UgcMusicBriefInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from UgcMusicBriefInfo.proto</summary>
  public static partial class UgcMusicBriefInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for UgcMusicBriefInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UgcMusicBriefInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdVZ2NNdXNpY0JyaWVmSW5mby5wcm90bxIfV2VlZHdhY2tlci5TaGFyZWQu",
            "TmV0d29yay5Qcm90byLoAwoRVWdjTXVzaWNCcmllZkluZm8SEwoLY3JlYXRl",
            "X3RpbWUYDCABKA0SEQoJY2FuX3NoYXJlGA8gASgIEhAKCHBvc2l0aW9uGAUg",
            "ASgNEhwKE1VuazMzMDBfSkVFQkZQRkVISEcYjgQgAygNEhgKEG11c2ljX25v",
            "dGVfY291bnQYKiABKA0SGwoTVW5rMzMwMF9IS0JIQUlNT0JLTxhBIAMoDRIT",
            "CgpzaGFyZV90aW1lGNkMIAEoDRIcChRpbXBvcnRfZnJvbV91Z2NfZ3VpZBgN",
            "IAEoBBIWCg5tdXNpY19zaGFyZV9pZBgIIAEoBBINCgVzY29yZRgHIAEoDRIO",
            "CgZzZXR0bGUYAyABKAgSDwoHdmVyc2lvbhgLIAEoDRIXCg9pc19wc25fcGxh",
            "dGZvcm0YAiABKAgSGwoTVW5rMzMwMF9QTE5PRk9IRkFQRRgEIAEoDRIbChNV",
            "bmszMzAwX0NDTU1QQUhJTURPGF8gASgNEhcKD2F1dGhvcl9uaWNrbmFtZRgJ",
            "IAEoCRIQCghtdXNpY19pZBgGIAEoDRIbChNVbmszMzAwX0dETkFQTkFJTkJB",
            "GAogASgIEhEKCW1heF9zY29yZRgBIAEoDRIbChNVbmszMzAwX09CQk1DRkFE",
            "TklOGA4gASgNYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.UgcMusicBriefInfo), global::Weedwacker.Shared.Network.Proto.UgcMusicBriefInfo.Parser, new[]{ "CreateTime", "CanShare", "Position", "Unk3300JEEBFPFEHHG", "MusicNoteCount", "Unk3300HKBHAIMOBKO", "ShareTime", "ImportFromUgcGuid", "MusicShareId", "Score", "Settle", "Version", "IsPsnPlatform", "Unk3300PLNOFOHFAPE", "Unk3300CCMMPAHIMDO", "AuthorNickname", "MusicId", "Unk3300GDNAPNAINBA", "MaxScore", "Unk3300OBBMCFADNIN" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UgcMusicBriefInfo : pb::IMessage<UgcMusicBriefInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UgcMusicBriefInfo> _parser = new pb::MessageParser<UgcMusicBriefInfo>(() => new UgcMusicBriefInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UgcMusicBriefInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.UgcMusicBriefInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UgcMusicBriefInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UgcMusicBriefInfo(UgcMusicBriefInfo other) : this() {
      createTime_ = other.createTime_;
      canShare_ = other.canShare_;
      position_ = other.position_;
      unk3300JEEBFPFEHHG_ = other.unk3300JEEBFPFEHHG_.Clone();
      musicNoteCount_ = other.musicNoteCount_;
      unk3300HKBHAIMOBKO_ = other.unk3300HKBHAIMOBKO_.Clone();
      shareTime_ = other.shareTime_;
      importFromUgcGuid_ = other.importFromUgcGuid_;
      musicShareId_ = other.musicShareId_;
      score_ = other.score_;
      settle_ = other.settle_;
      version_ = other.version_;
      isPsnPlatform_ = other.isPsnPlatform_;
      unk3300PLNOFOHFAPE_ = other.unk3300PLNOFOHFAPE_;
      unk3300CCMMPAHIMDO_ = other.unk3300CCMMPAHIMDO_;
      authorNickname_ = other.authorNickname_;
      musicId_ = other.musicId_;
      unk3300GDNAPNAINBA_ = other.unk3300GDNAPNAINBA_;
      maxScore_ = other.maxScore_;
      unk3300OBBMCFADNIN_ = other.unk3300OBBMCFADNIN_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UgcMusicBriefInfo Clone() {
      return new UgcMusicBriefInfo(this);
    }

    /// <summary>Field number for the "create_time" field.</summary>
    public const int CreateTimeFieldNumber = 12;
    private uint createTime_;
    /// <summary>
    /// Unk3300_OJOKFBJALIJ
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CreateTime {
      get { return createTime_; }
      set {
        createTime_ = value;
      }
    }

    /// <summary>Field number for the "can_share" field.</summary>
    public const int CanShareFieldNumber = 15;
    private bool canShare_;
    /// <summary>
    /// Unk3300_NCDKCNOLGKB
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CanShare {
      get { return canShare_; }
      set {
        canShare_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 5;
    private uint position_;
    /// <summary>
    /// Unk3300_KMMBLIMKJCM
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_JEEBFPFEHHG" field.</summary>
    public const int Unk3300JEEBFPFEHHGFieldNumber = 526;
    private static readonly pb::FieldCodec<uint> _repeated_unk3300JEEBFPFEHHG_codec
        = pb::FieldCodec.ForUInt32(4210);
    private readonly pbc::RepeatedField<uint> unk3300JEEBFPFEHHG_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Unk3300JEEBFPFEHHG {
      get { return unk3300JEEBFPFEHHG_; }
    }

    /// <summary>Field number for the "music_note_count" field.</summary>
    public const int MusicNoteCountFieldNumber = 42;
    private uint musicNoteCount_;
    /// <summary>
    /// Unk3300_EGIGIOOKBAB
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MusicNoteCount {
      get { return musicNoteCount_; }
      set {
        musicNoteCount_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_HKBHAIMOBKO" field.</summary>
    public const int Unk3300HKBHAIMOBKOFieldNumber = 65;
    private static readonly pb::FieldCodec<uint> _repeated_unk3300HKBHAIMOBKO_codec
        = pb::FieldCodec.ForUInt32(522);
    private readonly pbc::RepeatedField<uint> unk3300HKBHAIMOBKO_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Unk3300HKBHAIMOBKO {
      get { return unk3300HKBHAIMOBKO_; }
    }

    /// <summary>Field number for the "share_time" field.</summary>
    public const int ShareTimeFieldNumber = 1625;
    private uint shareTime_;
    /// <summary>
    /// Unk3300_MBKDGBNFPOA
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ShareTime {
      get { return shareTime_; }
      set {
        shareTime_ = value;
      }
    }

    /// <summary>Field number for the "import_from_ugc_guid" field.</summary>
    public const int ImportFromUgcGuidFieldNumber = 13;
    private ulong importFromUgcGuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ImportFromUgcGuid {
      get { return importFromUgcGuid_; }
      set {
        importFromUgcGuid_ = value;
      }
    }

    /// <summary>Field number for the "music_share_id" field.</summary>
    public const int MusicShareIdFieldNumber = 8;
    private ulong musicShareId_;
    /// <summary>
    /// ugc_guid
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong MusicShareId {
      get { return musicShareId_; }
      set {
        musicShareId_ = value;
      }
    }

    /// <summary>Field number for the "score" field.</summary>
    public const int ScoreFieldNumber = 7;
    private uint score_;
    /// <summary>
    /// Unk3300_PBENMAHHGIL
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Score {
      get { return score_; }
      set {
        score_ = value;
      }
    }

    /// <summary>Field number for the "settle" field.</summary>
    public const int SettleFieldNumber = 3;
    private bool settle_;
    /// <summary>
    /// Unk3300_FKIGPAJFPLG
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Settle {
      get { return settle_; }
      set {
        settle_ = value;
      }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 11;
    private uint version_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    /// <summary>Field number for the "is_psn_platform" field.</summary>
    public const int IsPsnPlatformFieldNumber = 2;
    private bool isPsnPlatform_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsPsnPlatform {
      get { return isPsnPlatform_; }
      set {
        isPsnPlatform_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_PLNOFOHFAPE" field.</summary>
    public const int Unk3300PLNOFOHFAPEFieldNumber = 4;
    private uint unk3300PLNOFOHFAPE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Unk3300PLNOFOHFAPE {
      get { return unk3300PLNOFOHFAPE_; }
      set {
        unk3300PLNOFOHFAPE_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_CCMMPAHIMDO" field.</summary>
    public const int Unk3300CCMMPAHIMDOFieldNumber = 95;
    private uint unk3300CCMMPAHIMDO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Unk3300CCMMPAHIMDO {
      get { return unk3300CCMMPAHIMDO_; }
      set {
        unk3300CCMMPAHIMDO_ = value;
      }
    }

    /// <summary>Field number for the "author_nickname" field.</summary>
    public const int AuthorNicknameFieldNumber = 9;
    private string authorNickname_ = "";
    /// <summary>
    /// creator_nickname
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AuthorNickname {
      get { return authorNickname_; }
      set {
        authorNickname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "music_id" field.</summary>
    public const int MusicIdFieldNumber = 6;
    private uint musicId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MusicId {
      get { return musicId_; }
      set {
        musicId_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_GDNAPNAINBA" field.</summary>
    public const int Unk3300GDNAPNAINBAFieldNumber = 10;
    private bool unk3300GDNAPNAINBA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unk3300GDNAPNAINBA {
      get { return unk3300GDNAPNAINBA_; }
      set {
        unk3300GDNAPNAINBA_ = value;
      }
    }

    /// <summary>Field number for the "max_score" field.</summary>
    public const int MaxScoreFieldNumber = 1;
    private uint maxScore_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MaxScore {
      get { return maxScore_; }
      set {
        maxScore_ = value;
      }
    }

    /// <summary>Field number for the "Unk3300_OBBMCFADNIN" field.</summary>
    public const int Unk3300OBBMCFADNINFieldNumber = 14;
    private uint unk3300OBBMCFADNIN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Unk3300OBBMCFADNIN {
      get { return unk3300OBBMCFADNIN_; }
      set {
        unk3300OBBMCFADNIN_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UgcMusicBriefInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UgcMusicBriefInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CreateTime != other.CreateTime) return false;
      if (CanShare != other.CanShare) return false;
      if (Position != other.Position) return false;
      if(!unk3300JEEBFPFEHHG_.Equals(other.unk3300JEEBFPFEHHG_)) return false;
      if (MusicNoteCount != other.MusicNoteCount) return false;
      if(!unk3300HKBHAIMOBKO_.Equals(other.unk3300HKBHAIMOBKO_)) return false;
      if (ShareTime != other.ShareTime) return false;
      if (ImportFromUgcGuid != other.ImportFromUgcGuid) return false;
      if (MusicShareId != other.MusicShareId) return false;
      if (Score != other.Score) return false;
      if (Settle != other.Settle) return false;
      if (Version != other.Version) return false;
      if (IsPsnPlatform != other.IsPsnPlatform) return false;
      if (Unk3300PLNOFOHFAPE != other.Unk3300PLNOFOHFAPE) return false;
      if (Unk3300CCMMPAHIMDO != other.Unk3300CCMMPAHIMDO) return false;
      if (AuthorNickname != other.AuthorNickname) return false;
      if (MusicId != other.MusicId) return false;
      if (Unk3300GDNAPNAINBA != other.Unk3300GDNAPNAINBA) return false;
      if (MaxScore != other.MaxScore) return false;
      if (Unk3300OBBMCFADNIN != other.Unk3300OBBMCFADNIN) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CreateTime != 0) hash ^= CreateTime.GetHashCode();
      if (CanShare != false) hash ^= CanShare.GetHashCode();
      if (Position != 0) hash ^= Position.GetHashCode();
      hash ^= unk3300JEEBFPFEHHG_.GetHashCode();
      if (MusicNoteCount != 0) hash ^= MusicNoteCount.GetHashCode();
      hash ^= unk3300HKBHAIMOBKO_.GetHashCode();
      if (ShareTime != 0) hash ^= ShareTime.GetHashCode();
      if (ImportFromUgcGuid != 0UL) hash ^= ImportFromUgcGuid.GetHashCode();
      if (MusicShareId != 0UL) hash ^= MusicShareId.GetHashCode();
      if (Score != 0) hash ^= Score.GetHashCode();
      if (Settle != false) hash ^= Settle.GetHashCode();
      if (Version != 0) hash ^= Version.GetHashCode();
      if (IsPsnPlatform != false) hash ^= IsPsnPlatform.GetHashCode();
      if (Unk3300PLNOFOHFAPE != 0) hash ^= Unk3300PLNOFOHFAPE.GetHashCode();
      if (Unk3300CCMMPAHIMDO != 0) hash ^= Unk3300CCMMPAHIMDO.GetHashCode();
      if (AuthorNickname.Length != 0) hash ^= AuthorNickname.GetHashCode();
      if (MusicId != 0) hash ^= MusicId.GetHashCode();
      if (Unk3300GDNAPNAINBA != false) hash ^= Unk3300GDNAPNAINBA.GetHashCode();
      if (MaxScore != 0) hash ^= MaxScore.GetHashCode();
      if (Unk3300OBBMCFADNIN != 0) hash ^= Unk3300OBBMCFADNIN.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MaxScore != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MaxScore);
      }
      if (IsPsnPlatform != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsPsnPlatform);
      }
      if (Settle != false) {
        output.WriteRawTag(24);
        output.WriteBool(Settle);
      }
      if (Unk3300PLNOFOHFAPE != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Unk3300PLNOFOHFAPE);
      }
      if (Position != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Position);
      }
      if (MusicId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(MusicId);
      }
      if (Score != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(Score);
      }
      if (MusicShareId != 0UL) {
        output.WriteRawTag(64);
        output.WriteUInt64(MusicShareId);
      }
      if (AuthorNickname.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(AuthorNickname);
      }
      if (Unk3300GDNAPNAINBA != false) {
        output.WriteRawTag(80);
        output.WriteBool(Unk3300GDNAPNAINBA);
      }
      if (Version != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(Version);
      }
      if (CreateTime != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(CreateTime);
      }
      if (ImportFromUgcGuid != 0UL) {
        output.WriteRawTag(104);
        output.WriteUInt64(ImportFromUgcGuid);
      }
      if (Unk3300OBBMCFADNIN != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(Unk3300OBBMCFADNIN);
      }
      if (CanShare != false) {
        output.WriteRawTag(120);
        output.WriteBool(CanShare);
      }
      if (MusicNoteCount != 0) {
        output.WriteRawTag(208, 2);
        output.WriteUInt32(MusicNoteCount);
      }
      unk3300HKBHAIMOBKO_.WriteTo(output, _repeated_unk3300HKBHAIMOBKO_codec);
      if (Unk3300CCMMPAHIMDO != 0) {
        output.WriteRawTag(248, 5);
        output.WriteUInt32(Unk3300CCMMPAHIMDO);
      }
      unk3300JEEBFPFEHHG_.WriteTo(output, _repeated_unk3300JEEBFPFEHHG_codec);
      if (ShareTime != 0) {
        output.WriteRawTag(200, 101);
        output.WriteUInt32(ShareTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MaxScore != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MaxScore);
      }
      if (IsPsnPlatform != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsPsnPlatform);
      }
      if (Settle != false) {
        output.WriteRawTag(24);
        output.WriteBool(Settle);
      }
      if (Unk3300PLNOFOHFAPE != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Unk3300PLNOFOHFAPE);
      }
      if (Position != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Position);
      }
      if (MusicId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(MusicId);
      }
      if (Score != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(Score);
      }
      if (MusicShareId != 0UL) {
        output.WriteRawTag(64);
        output.WriteUInt64(MusicShareId);
      }
      if (AuthorNickname.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(AuthorNickname);
      }
      if (Unk3300GDNAPNAINBA != false) {
        output.WriteRawTag(80);
        output.WriteBool(Unk3300GDNAPNAINBA);
      }
      if (Version != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(Version);
      }
      if (CreateTime != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(CreateTime);
      }
      if (ImportFromUgcGuid != 0UL) {
        output.WriteRawTag(104);
        output.WriteUInt64(ImportFromUgcGuid);
      }
      if (Unk3300OBBMCFADNIN != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(Unk3300OBBMCFADNIN);
      }
      if (CanShare != false) {
        output.WriteRawTag(120);
        output.WriteBool(CanShare);
      }
      if (MusicNoteCount != 0) {
        output.WriteRawTag(208, 2);
        output.WriteUInt32(MusicNoteCount);
      }
      unk3300HKBHAIMOBKO_.WriteTo(ref output, _repeated_unk3300HKBHAIMOBKO_codec);
      if (Unk3300CCMMPAHIMDO != 0) {
        output.WriteRawTag(248, 5);
        output.WriteUInt32(Unk3300CCMMPAHIMDO);
      }
      unk3300JEEBFPFEHHG_.WriteTo(ref output, _repeated_unk3300JEEBFPFEHHG_codec);
      if (ShareTime != 0) {
        output.WriteRawTag(200, 101);
        output.WriteUInt32(ShareTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CreateTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CreateTime);
      }
      if (CanShare != false) {
        size += 1 + 1;
      }
      if (Position != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Position);
      }
      size += unk3300JEEBFPFEHHG_.CalculateSize(_repeated_unk3300JEEBFPFEHHG_codec);
      if (MusicNoteCount != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(MusicNoteCount);
      }
      size += unk3300HKBHAIMOBKO_.CalculateSize(_repeated_unk3300HKBHAIMOBKO_codec);
      if (ShareTime != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(ShareTime);
      }
      if (ImportFromUgcGuid != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ImportFromUgcGuid);
      }
      if (MusicShareId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MusicShareId);
      }
      if (Score != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Score);
      }
      if (Settle != false) {
        size += 1 + 1;
      }
      if (Version != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Version);
      }
      if (IsPsnPlatform != false) {
        size += 1 + 1;
      }
      if (Unk3300PLNOFOHFAPE != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Unk3300PLNOFOHFAPE);
      }
      if (Unk3300CCMMPAHIMDO != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(Unk3300CCMMPAHIMDO);
      }
      if (AuthorNickname.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AuthorNickname);
      }
      if (MusicId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MusicId);
      }
      if (Unk3300GDNAPNAINBA != false) {
        size += 1 + 1;
      }
      if (MaxScore != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MaxScore);
      }
      if (Unk3300OBBMCFADNIN != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Unk3300OBBMCFADNIN);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UgcMusicBriefInfo other) {
      if (other == null) {
        return;
      }
      if (other.CreateTime != 0) {
        CreateTime = other.CreateTime;
      }
      if (other.CanShare != false) {
        CanShare = other.CanShare;
      }
      if (other.Position != 0) {
        Position = other.Position;
      }
      unk3300JEEBFPFEHHG_.Add(other.unk3300JEEBFPFEHHG_);
      if (other.MusicNoteCount != 0) {
        MusicNoteCount = other.MusicNoteCount;
      }
      unk3300HKBHAIMOBKO_.Add(other.unk3300HKBHAIMOBKO_);
      if (other.ShareTime != 0) {
        ShareTime = other.ShareTime;
      }
      if (other.ImportFromUgcGuid != 0UL) {
        ImportFromUgcGuid = other.ImportFromUgcGuid;
      }
      if (other.MusicShareId != 0UL) {
        MusicShareId = other.MusicShareId;
      }
      if (other.Score != 0) {
        Score = other.Score;
      }
      if (other.Settle != false) {
        Settle = other.Settle;
      }
      if (other.Version != 0) {
        Version = other.Version;
      }
      if (other.IsPsnPlatform != false) {
        IsPsnPlatform = other.IsPsnPlatform;
      }
      if (other.Unk3300PLNOFOHFAPE != 0) {
        Unk3300PLNOFOHFAPE = other.Unk3300PLNOFOHFAPE;
      }
      if (other.Unk3300CCMMPAHIMDO != 0) {
        Unk3300CCMMPAHIMDO = other.Unk3300CCMMPAHIMDO;
      }
      if (other.AuthorNickname.Length != 0) {
        AuthorNickname = other.AuthorNickname;
      }
      if (other.MusicId != 0) {
        MusicId = other.MusicId;
      }
      if (other.Unk3300GDNAPNAINBA != false) {
        Unk3300GDNAPNAINBA = other.Unk3300GDNAPNAINBA;
      }
      if (other.MaxScore != 0) {
        MaxScore = other.MaxScore;
      }
      if (other.Unk3300OBBMCFADNIN != 0) {
        Unk3300OBBMCFADNIN = other.Unk3300OBBMCFADNIN;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MaxScore = input.ReadUInt32();
            break;
          }
          case 16: {
            IsPsnPlatform = input.ReadBool();
            break;
          }
          case 24: {
            Settle = input.ReadBool();
            break;
          }
          case 32: {
            Unk3300PLNOFOHFAPE = input.ReadUInt32();
            break;
          }
          case 40: {
            Position = input.ReadUInt32();
            break;
          }
          case 48: {
            MusicId = input.ReadUInt32();
            break;
          }
          case 56: {
            Score = input.ReadUInt32();
            break;
          }
          case 64: {
            MusicShareId = input.ReadUInt64();
            break;
          }
          case 74: {
            AuthorNickname = input.ReadString();
            break;
          }
          case 80: {
            Unk3300GDNAPNAINBA = input.ReadBool();
            break;
          }
          case 88: {
            Version = input.ReadUInt32();
            break;
          }
          case 96: {
            CreateTime = input.ReadUInt32();
            break;
          }
          case 104: {
            ImportFromUgcGuid = input.ReadUInt64();
            break;
          }
          case 112: {
            Unk3300OBBMCFADNIN = input.ReadUInt32();
            break;
          }
          case 120: {
            CanShare = input.ReadBool();
            break;
          }
          case 336: {
            MusicNoteCount = input.ReadUInt32();
            break;
          }
          case 522:
          case 520: {
            unk3300HKBHAIMOBKO_.AddEntriesFrom(input, _repeated_unk3300HKBHAIMOBKO_codec);
            break;
          }
          case 760: {
            Unk3300CCMMPAHIMDO = input.ReadUInt32();
            break;
          }
          case 4210:
          case 4208: {
            unk3300JEEBFPFEHHG_.AddEntriesFrom(input, _repeated_unk3300JEEBFPFEHHG_codec);
            break;
          }
          case 13000: {
            ShareTime = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MaxScore = input.ReadUInt32();
            break;
          }
          case 16: {
            IsPsnPlatform = input.ReadBool();
            break;
          }
          case 24: {
            Settle = input.ReadBool();
            break;
          }
          case 32: {
            Unk3300PLNOFOHFAPE = input.ReadUInt32();
            break;
          }
          case 40: {
            Position = input.ReadUInt32();
            break;
          }
          case 48: {
            MusicId = input.ReadUInt32();
            break;
          }
          case 56: {
            Score = input.ReadUInt32();
            break;
          }
          case 64: {
            MusicShareId = input.ReadUInt64();
            break;
          }
          case 74: {
            AuthorNickname = input.ReadString();
            break;
          }
          case 80: {
            Unk3300GDNAPNAINBA = input.ReadBool();
            break;
          }
          case 88: {
            Version = input.ReadUInt32();
            break;
          }
          case 96: {
            CreateTime = input.ReadUInt32();
            break;
          }
          case 104: {
            ImportFromUgcGuid = input.ReadUInt64();
            break;
          }
          case 112: {
            Unk3300OBBMCFADNIN = input.ReadUInt32();
            break;
          }
          case 120: {
            CanShare = input.ReadBool();
            break;
          }
          case 336: {
            MusicNoteCount = input.ReadUInt32();
            break;
          }
          case 522:
          case 520: {
            unk3300HKBHAIMOBKO_.AddEntriesFrom(ref input, _repeated_unk3300HKBHAIMOBKO_codec);
            break;
          }
          case 760: {
            Unk3300CCMMPAHIMDO = input.ReadUInt32();
            break;
          }
          case 4210:
          case 4208: {
            unk3300JEEBFPFEHHG_.AddEntriesFrom(ref input, _repeated_unk3300JEEBFPFEHHG_codec);
            break;
          }
          case 13000: {
            ShareTime = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
